### ISSUE TITLE
Documentacion proyecto: (presupuesto_cliente)

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#10]
Se debe ajustar el readme del repositorio para seguir los lineamientos definidos a nivel interno en la Oficina Asesora de Sistemas

**Comment by mcguegi** [comment]
Se añade enlace a los mockups. Sin embargo queda pendiente subir imagenes de los mismos al repositorio de documentación del proyecto dado que este todavía no ha sido creado.

**Comment by Soulfilip-UD** [comment]
En la construcción del repositorio de documentación se tendrán en cuenta todas las imágenes referentes y links donde reposa la información. Tarea Finalizada. Proceeding to close Issue 👾
