### ISSUE TITLE
**presupuesto cliente** Integrar cliente modificaciones con el back de modificaciones - 20 horas - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/presupuesto_cliente#101]
- [x] ajustar api para estandar de mongo
- [x] ajustar funciones de request para consumir api

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/commit/abe73bf5f40b67a2abaeff5c1576ea24587d4c95 con ayuda de @davidmm07 se ajustan los nombres de los campos de las colecciones al estandar de la oficina (minusculas con "_" como caracter se separación)

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/4b29e37e47c09c50c84ef2b4e7d39a0e84dae8d8 se agregan parametros y tipados para el registro de modificaciones

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/5a2e1fd7467678f97284d1609f94cc1feb19bf4a se generaliza funcion de registro de movimientos

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/commit/21fbecc71addff250fc18bf9cf2fbac11af0098c se ajusta afectacion para la generalizacion

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/commit/972e2d09edf0b4886ddeffe1773649d348ff62c3 se ajustan afectaciones de las modificaciones tomando en cuenta que muchas de estas se hacen en una sola rama del arbol

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/c7afb8a4ce335f3fbf9fc971540e545af00db8a2 se ajusta el algoritmo de transaccion para registro de modificaciones para que admita las cuentas crédito y lea de forma parametrica su afectacion

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/movimientos_crud/commit/02a3b6716f9ed70553801fc78e6eca85ea31410e se ajustan tipos de movimiento para que permitan retornar parametros dinamicos

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/commit/4a0c8cb27b57f09048e40f133948fc67bb77258c se agrega la afectación párametrica de un traslado

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/movimientos_crud/commit/02a3b6716f9ed70553801fc78e6eca85ea31410e se ajustan parametros para los movimientos

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/commit/041f0236424ca900c1766b3ab54324f5b0d7098b se ajustan serviciosde comprobación de balance para las modificaciones

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/eaa64040427a4503130962a23e6f4324aafd3883 se ajusta servicio de simulación de balanace para generar previews del balanace del arbol sin guaradar datos en la db

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/pull/129 se realiza pr a mongo crud

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/pull/36 se realiza pr a mid

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/movimientos_crud/pull/39 se realiza pr a movimientos crud

**Comment by miguelramirez93** [comment]
tarea finalizada @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Se revisado el código y se ha aprobado, al desplegar no he logrado visualizar la funcionalidad tampoco en test, no encuentro luces de la apariencia del componente en funcionamiento.

Mientras el desarrollo no este estable en test es difcil evualar el estado de la tarea, ya he desplegado todos los cambios, actualizado los endpoints de de los diferentes APIs. Una anotación importante es que el API de movimientos presenta un error como Unknow error y tampoco se ha evidenciado su funcionamiento. 

Devuelvo la tarea a TODO hasta que pueda realizar las pruebas mencionadas.

Moving to TODO ... 🚶

**Comment by Soulfilip-UD** [comment]
Se realizan las pruebas, el desarrollo coincide con las HU, quedan los ajustes que se realizan en el Issue #156 

Proceeding to close Issue 👾
