### ISSUE TITLE
Integración cliente con Mid API de rubros

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/presupuesto_cliente#11]
- [x] Desarrollo e Implementación de Request Manager General.

- [x] Desarrollo de módulos de Registro, Borrado y Consulta de Rubros.

- [x] Documentación de funciones

**Comment by Soulfilip-UD** [comment]
Entiendo que hubo una muy buena documentación a nivel de código, Escelente trabajo!
Proceeding to close Issue :space_invader:
