### ISSUE TITLE
Ajustes  hito 1 (Arbol de rubros, apropiaciones y necesidades)

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#113]
En el issue actual estoy adjuntando la lista de ajustes que se vieron el día de ayer y hoy en los módulos de arbol de rubros, apropiaciones iniciales y necesidades. Basado en estos ajustes se estaría cerrando el entregable del hito 1.

### Arbol de rubros y Apropiaciones

- [x] Cuando un rubro padre se le han borrado los hijos y no ha sido usado en una apropiación se debe levantar el bloqueo que permite eliminarlo.

- [x] Revisar el bloqueo cuando el rubro se asigna a una apropiación

- [x] Ajustar el tamaño de los cajas de consultar apropiación y preasignar apropiaciones, para que queden del mismo tamaño, dar un tamaño fijo.

- [x] En la vista de preasignar apropiaciones solo se debe poder trabajar sobre la siguiente vigencia, por lo que debe traer un dato no modificable que diga 2020

- [x] En la vista de consultar apropiación, los rubros deben estar asociados al rubro padre, actualmente se ven desorganizado.
- [x] Parametrizar Rubros (api) que permita cambiar Comparación de Ingresos y Egresos

**Comment by DianaPatriciaRamirez** [comment]
Adicionalmente, hacen falta los siguientes ajustes para tener en cuenta en la entrega del Hito 1 de Kronos: @Soulfilip-UD @mcrubianot @davidmm07 @miguelramirez93 @corio27 @jairolh 

- [ ] En la creación de los rubros debe permitir editar a cualquier nivel, siempre y cuando no tenga asignado una apropiación y/o movimientos.

- [ ] Generar alertas tanto para la edición (el sistema debe notificar que hubo una actualización del rubro), como en la creación definitiva de los rubros. 

- [ ] Unificar tamaño de fuentes.

- [ ] En el campo "Detalle del rubro", en el recuadro Centro Gestor debe mostrar el código de la entidad y en el recuadro de Área Funcional debe mostrar el código y el nombre de la Unidad ejecutora. Por ejemplo: Centro Gestor: 230 y Área Funcional: 01-Rector.

- [ ] Tener en cuenta las tildes y las separaciones entre palabras.

Por último se aclara que el cierre definitivo para la entrega del Hito 1, depende de las pruebas: funcionales, revisión de la calidad del código, carga, stress, entre otras; así mismo, depende de lo solitado por el usuario y su respectiva revisión.

**Comment by davidmm07** [comment]
Generar alertas tanto para la edición (el sistema debe notificar que hubo una actualización del rubro), como en la creación definitiva de los rubros. **el sistema ya lo hace**  https://github.com/udistrital/presupuesto_cliente/blob/21da3bc25254d7de6983d0cdb17a043b15802b3f/src/app/pages/plan-cuentas/rubros/rubros.component.ts#L119
https://github.com/udistrital/presupuesto_cliente/blob/21da3bc25254d7de6983d0cdb17a043b15802b3f/src/app/pages/plan-cuentas/rubros/rubros.component.ts#L145

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/commit/595904d95b9b8a6139962f00b1d8e0b62a11e4e8 se ajusta valor de la apropiacion siempre mayor a 0

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/commit/5f2e2503490e19e84083cef35d72b569328ef8a0 se ajusta el bloqueo de eliminación de rubros si este tiene hojas o apropiaciones

**Comment by davidmm07** [comment]
A revision @Soulfilip-UD

**Comment by DianaPatriciaRamirez** [comment]
De acuerdo a revisión realizada al desarrollo del hito 1 el día 25 de octubre, surgen las siguientes observaciones:

- [ ] Corrección componente de verificación de pre-asignación inicial.

- [ ] Correcciones [Correcciones Presupuesto](https://docs.google.com/spreadsheets/d/1zPCUYFmF0RfyXXgHluaowNSKrhT-F3xrn-K5Xadp1zA/edit#gid=2049717302)

- [ ] Verificar si ya se realizaron las pruebas unitarias, o si no tenerlas finalizadas para el próximo 1 de noviembre @miguelramirez93 

Rubros, preasignación y apropiaciones deben estar finalizadas para el 1 noviembre, así mismo, las pruebas unitarias deben estar terminadas para el viernes 1 de noviembre.

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/pull/46 ; https://github.com/udistrital/plan_cuentas_mongo_crud/pull/135 ; 
https://github.com/udistrital/presupuesto_cliente/pull/135 se realizan pull request con las correcciones faltantes y sugerencias realizadas para el hito 1 en cuanto a plan de cuentas

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/pull/137 se añade comprobación de eliminado o registro de nodos al arbol de rubros, se bloquea botón de eliminado cuando el rubro tiene hijos o tiene apropiaciones, se bloquea  "añadir nodo" si el nodo hoja posee apropiaciones en el historial de vigencias.

**Comment by DianaPatriciaRamirez** [comment]
Se recomienda realizar los ajustes que correspondan, de acuerdo a la revisión funcional realizada por la analista de requerimientos Maria Claudia Rubiano @mcrubianot y por el Centro de Servicios de la OAS; respecto a los módulos: rubros, preasignación, apropiación y productos. Los ajustes deben estar finalizados para este viernes 15 de noviembre. A continuación se adjuntan los enlaces para su revisión:

- [ ] [https://github.com/udistrital/financiera_cliente/issues/605](url)

- [ ] [https://tuleap.udistrital.edu.co/plugins/tracker/?aid=32790](url)

Tarea asignada a: @Soulfilip-UD @miguelramirez93 @davidmm07

**Comment by Soulfilip-UD** [comment]
Se realizaron pruebas hasta el 10mo nivel, revisar el [Issue #158](https://github.com/udistrital/plan_cuentas_mongo_crud/issues/158)

Tarea realizada, revisada y finalizada
Proceeding to close Issue 👾 
<img width="614" alt="Screen Shot 2019-12-05 at 11 49 40 PM" src="https://user-images.githubusercontent.com/50924615/70296988-54a9ee00-17ba-11ea-992f-826a1aa2d88d.png">
