### ISSUE TITLE
**presupuesto_cliente** asociar productos al arbol de apropiaciones

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#121]
- [x] Generar proceso de asociar productos al arbol de apropiaciones
- [x] Generar restricciones necesarias para el proceso

**Comment by davidmm07** [comment]
Tarea a revision @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
En este momento se hace la anotación que en últimos despliegues se veia la pestaña del componente, más actualmente luce que el endpoint no recibe productos entra en error y todo se blankea, revisar si es un error del API por mi parte revisare el WSO2.
<img width="1343" alt="Screen Shot 2019-10-29 at 8 04 49 AM" src="https://user-images.githubusercontent.com/50924615/67769750-0408dd80-fa23-11e9-9744-f614c1a83245.png">

**Comment by davidmm07** [comment]
Se corrige error en el ultimo PR

**Comment by Soulfilip-UD** [comment]
Es correcto el desarrollo esta estable y se puede revisar en test todo ok 👍 

Tarea Finalizada 
Proceeding to close Issue 👾
