### ISSUE TITLE
**presupuesto cliente** Actualizar menu principal con fuentes, productos, modificaciones, CDp y CRP - 1 hora - David

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#127]
-[x] Actualizar menu principal con fuentes, productos, modificaciones, CDp y CRP

**Comment by davidmm07** [comment]
Tarea a revisión @Soulfilip

**Comment by Soulfilip-UD** [comment]
Menu actualizado 
<img width="270" alt="Screen Shot 2019-10-29 at 8 07 34 AM" src="https://user-images.githubusercontent.com/50924615/67769863-331f4f00-fa23-11e9-8875-035a7694fd20.png">

Proceeding to close Issue 👾
