### ISSUE TITLE
Desarrollo hito 2 (Fuentes): ajustar de acuerdo al modelo del plan de adquisiciones y a las historias de usuario. 

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#148]
- [x] Adaptar el cliente de fuentes a las nuevas peticiones backend (id, ue, vigencia) 4h
- [x] distribucion de saldos como documento presupuestal, 8h
- [x] edición, validar eliminación 5h
- [x] columna con código y estado de la fuente, 1h
- [x] ajustes alertas 1h
- [x]  edición, validar eliminación fuente cuando no haya sido distribuída 5h
- [x] validación de la apropiación actividad Vs saldo de la fuente, 8h
- [x] asignar valores de la fuente a las actividades, 8h NO APLICA (Se hala información de la bodega)
- [x] distribuir el valor total del rubro en las fuentes seleccionadas 5h NO APLICA 
- [x] distribuir el valor total de las fuentes en las dependencias asociadas 5h NO APLICA

**Comment by davidmm07** [comment]
Se revisan las historias de usuarío, cabe aclarar que en ningun momento se menciona el tema de metas y actividades, sin embargo en una reunión con el usuario, para el tema de inversión  aclara que es importante para su negocio

**Comment by davidmm07** [comment]
https://github.com/udistrital/presupuesto_cliente/issues/162

**Comment by Soulfilip-UD** [comment]
- [ ] Tooltip en cada uno de los links

- [ ] Descripción de los iconos de fuentes

**Comment by DianaPatriciaRamirez** [comment]
De acuerdo a revisión del 15 de noviembre, se realizan las siguientes observaciones. Todos los ajustes se revisarán el lunes 18 de noviembre.

- [ ] En el campo "Código" revisar si hay restricciones para el ingreso de datos.
- [ ] Tipificar el mensaje de error en cada campo, las expresiones regulares. Por ejemplo: Cambiar alerta "**Este patrón no es aceptado" por "Formato incorrecto".
- [ ] Dejar en la parte superior, el botón "Regresar".
- [ ] En el campo "Vigencia", al seleccionarla debe mostrar el label 2019, por ejemplo. Adicionalmente, se debe incluir la opción "Todos".
- [ ] Las consultas de fuentes no están funcionando.

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 19 de noviembre, queda pendiente y este viernes 22 de noviembre ya se tendrá el módulo de fuentes de financiamiento al 100%:

1. - edición, validar eliminación fuente cuando no haya sido distribuída 5h
2. - validación de la apropiación actividad Vs saldo de la fuente, 8h
3. - Tooltip en cada uno de los links
4. - Descripción de los iconos de fuentes

**Comment by davidmm07** [comment]
![image](https://user-images.githubusercontent.com/15944053/69424900-bfa5f000-0cf7-11ea-9a34-965140623413.png)

se agrega validación apropiacion vs valor actividades, y validacion vs valor fuentes

**Comment by Soulfilip-UD** [comment]
- [ ] El popup Manager se estallo en la presentación al eliminar una fuente que ya estaba distribuida

- [ ] Felipe no le ha pasado la descripción a David

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 29 de noviembre surgen las siguientes observaciones:

- [ ] Dejar saldo de fuente

- [ ] En consulta de rubros por fuente, se debe discriminar por metas.

- [ ] Poner los títulos para cada ventana, en todo el sistema Kronos.

Se revisará Fuentes junto a modificaciones en la fuente, el próximo martes 3 de diciembre.

**Comment by Soulfilip-UD** [comment]
Ya revisado , y OK ! 
Revisar el desarrollo en test

**Comment by Soulfilip-UD** [comment]
Todo OK en Test , 

Proceeding to close Issue 👾

**Comment by DianaPatriciaRamirez** [comment]
En reunión del 6 de diciembre, se encuentras las siguientes observaciones:

- [ ] El sistema no debe permitir eliminar una fuente que ya este distribuida.

- [ ] En la consulta de fuentes de financiamiento, al "Editar" no muestra la información de: código, nombre y descripción. Sin embargo, al "Ver distribución" si aparece la información. El líder técnico @Soulfilip-UD indica que tampoco aparece la información en la base de datos pero en el sistema si se observan varias fuentes creadas. 

- [ ] Al crear una fuente y queda con vigencia "0", no debería visualizar información al darle clic en  "Ver distribución". 

- [ ] Al crear una fuente, el sistema debería enviar a la ventana de consulta.

- [ ] Fuentes creadas sin vigencia y que aparece en cero "0", debería cambiar el mensaje por "sin vigencia asignada".

Se revisará nuevamente a las 3:00 p.m.

**Comment by juancsr** [comment]
- [ ] Tilde : La fuente esta distribuida. -- Error al eliminar la fuente distribuida

- [ ] El saldo de la fuente en la distribución esta con un '-' de negativo

**Comment by Soulfilip-UD** [comment]
Se agrega la tilde que hacia falta. Tarea finalizada

Proceeding to close Issue 👾
