### ISSUE TITLE
Aprobar -DEPRECATED - a los repositorios no usados 

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#15]
Como existen repositorios fuera de uso, se procede a marcarlos con una marca de --DEPRECATED-- en el README, Carlos ya realizo el PR en los Repositorios que necesitan de esta acción, más por falta de permisos no pudo aprobarlos en todos.

**Comment by miguelramirez93** [comment]
se aprueba en https://github.com/udistrital/financiera_cliente/pull/544

**Comment by miguelramirez93** [comment]
se aprueba en https://github.com/udistrital/financiera_container_platform/pull/1

**Comment by miguelramirez93** [comment]
Se aprueba en https://github.com/udistrital/financiera_migracion/pull/1

**Comment by Soulfilip-UD** [comment]
Es necesario hacer review y aprobar  https://github.com/udistrital/presupuesto_crud/pull/14

**Comment by Soulfilip-UD** [comment]
Carlos comenta que los siguientes repositorios también necesitan de agregar la bandera de deprectaed:

- [x] API_FINANCIERA : https://github.com/udistrital/api_financiera

- [x] API_MID_FINANCIERA: https://github.com/udistrital/api_mid_financiera

**Comment by miguelramirez93** [comment]
Se han realizado los cambios

**Comment by Soulfilip-UD** [comment]
Cambios realizados. Proceeding to close Issue 👾
