### ISSUE TITLE
Ajustes Modificaciones 

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#156]
Ajustes 8 Nov 

- [x]  En la parte de finalizar el guardado de la modificación no se puede avanzar del step

- [x] Validar que el numero de documento no pueda ser negativo

- [x] El tipo documento debe alimentarse del api del core

- [x] Cambiar laber Sig. por Siguiente

- [x] Validar que el movimiento no supere el valor de la apropiación en todos los movimientos (revidar alertas de errores)

- [x] El formulario entra validando y se pinta todo de rojo

- [x]  Consultar el color tercero a usar para el titulo de gastos con Viviana y el rojo de cancelar

- [x] Socializar el tema de una suspensión ya que requiere un CDP @mcrubianot  y traslado requiere un CDP?
- [x] Validar que un rubro no se puede eliminar si recibe una modificación

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/c594210998658390ebe98c63212df08b5653641c se ajusta formato de respuesta de api ya que se realizaron modificaciones extra a la estructura de respuesta sin tener en cuenta lo que recibia el cliente ni los errores en apis externos.

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/presupuesto_cliente/commit/669da44c485e4c56296cfcb7384ffb5d030b2a2c se ajusta el formato de respuesta del api ya que este al cambiar en el api no permitia la comprobacion del balance de forma correcta y por ende no permitia avanzar al siguiente paso en el formulario.

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mongo_crud/commit/3a43b713ec94e14460e3961674a242199818e9a3 se ajusta el formato de respuesta de las funciones de simulación ya que estos ya estaban comprobando los saldos pero al no tener el correcto formato de respuesta el cliente no detectaba el error.

**Comment by miguelramirez93** [comment]
en https://github.com/udistrital/plan_cuentas_mid/commit/b5c01d07a396c3c2b00268131a7b8b60eefd4d2e se ajustan en mid api los formatos nuevos de respuesta de api mongo en comprobacion de saldos.

**Comment by miguelramirez93** [comment]
PR's: 

- https://github.com/udistrital/plan_cuentas_mid/pull/69
- https://github.com/udistrital/plan_cuentas_mongo_crud/pull/148

**Comment by DianaPatriciaRamirez** [comment]
De acuerdo a revisión hecha el 15 de noviembre, se revisaran los ajustes el próximo lunes 18 de noviembre:

- [ ] Revisar "Traslados" puesto que no está comprobando los saldos.
- [ ] En la numeración del acto, dejarlo alfa numérico.
- [ ] Una vez se genere el tipo de movimiento, el sistema traiga el numero de consecutivo que se genera para el CDP.
- [ ] En el registro, ocultar el botón de "Sig.", hasta que se agregue un movimiento.

**Comment by davidmm07** [comment]
- [ ] En caso de que se deba crear un rubro para asignarle una apropiación durante la vigencia con un movimiento, este se debe crear desde el árbol de apropiaciones y asignarle el valor de apropiación desde el movimiento adición.

- [ ] Realizar HU para el historico de los movimientos

- [ ] Mockups historico de los movimientos

***-------*****

- [ ] Las modificaciones a la fuente deben concibir tambien como un CRUD ( consultar y registrar)

**Comment by miguelramirez93** [comment]
PR https://github.com/udistrital/plan_cuentas_mid/pull/80

**Comment by miguelramirez93** [comment]
PR https://github.com/udistrital/plan_cuentas_mongo_crud/pull/159

**Comment by miguelramirez93** [comment]
PR https://github.com/udistrital/presupuesto_cliente/pull/196

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 29 de noviembre surgen las siguientes observaciones y pendientes:

- [ ] Suspensión y re-activación de un movimiento presupuestal.

- [ ] Faltan los filtros para que las consultas del listado de movimientos funcionen.

- [ ] Solicitar a Viviana mediante TuLeap, la asesoría con respecto al color rojo.

- [ ] Falta ajustar los títulos, en mayúsculas iniciales cuando corresponda.

- [ ] Consultar con usuario si desea que el tipo de modificación se visualice en la consulta histórico, cuando se realice la revisión funcional con ellos.

- [ ] Para la consulta histórico, falta agregar los campos: Número del CDP que se generó y Área Funcional. Ver HU - 46

Se revisará el 100% del módulo para el martes 3 de diciembre.

**Comment by miguelramirez93** [comment]
PR's
* https://github.com/udistrital/presupuesto_cliente/pull/226
* https://github.com/udistrital/plan_cuentas_mongo_crud/pull/171
* https://github.com/udistrital/plan_cuentas_mid/pull/91

**Comment by Soulfilip-UD** [comment]
- [ ] Cuadrar listado de CDP entre modificaciones y lo que ya habia realizado @juancsr

**Comment by Soulfilip-UD** [comment]
Se crea la tarjeta 
reuniones #34025 Sugerir color a escoger para los gastos en el componente balance de Kronos
https://tuleap.udistrital.edu.co/plugins/tracker/?aid=34025

**Comment by Soulfilip-UD** [comment]
Por el momento la tarea del color solicitado a @vaalvarezc queda pausada ya que:

Las paletas de los aplicativos cambiaron, cosa que apenas se definió el martes (3/12/2019) que nos reunimos con la jefe, entonces está pendiente por enviar los lineamientos de cada subsistema, pues antes se iba a manejar paleta por aplicativo, ahora es por categoría (académica, administrativa, financiera y conocimiento)

**Comment by Soulfilip-UD** [comment]
Se integra los CDP de modificaciones con los de solicitud de una necesidad en una sola consulta
<img width="580" alt="Screen Shot 2019-12-06 at 12 18 40 AM" src="https://user-images.githubusercontent.com/50924615/70298214-d9970680-17be-11ea-9e26-a88053a75bcb.png">
<img width="1089" alt="Screen Shot 2019-12-06 at 12 24 24 AM" src="https://user-images.githubusercontent.com/50924615/70298215-d9970680-17be-11ea-8996-c6d6f3460331.png">

**Comment by Soulfilip-UD** [comment]
- [ ] La fecha del documento debe quedar en formato : dd/mm/aaaa, actualmente está aaaa/mm/dd
<img width="167" alt="Screen Shot 2019-12-06 at 12 28 46 AM" src="https://user-images.githubusercontent.com/50924615/70298395-84a7c000-17bf-11ea-9629-63e2b4391de0.png">

**Comment by DianaPatriciaRamirez** [comment]
Se adicionan las siguientes observaciones a las postuladas anteriormente por el líder técnico @Soulfilip-UD:

- [ ] Suspensión y re-activación de un movimiento presupuestal.

- [ ] Faltan los filtros para que las consultas del listado de movimientos funcionen.

- [ ] Consultar con usuario si desea que el tipo de modificación se visualice en la consulta DETALLE, cuando se realice la revisión funcional con ellos.

Se revisará el martes 10 de diciembre al 100% terminado.

**Comment by Soulfilip-UD** [comment]
Quedamos por revisar los últimos ajustes en la reunión del 9 Dec/2019 a las 2pm, desplegado correctamente

**Comment by Soulfilip-UD** [comment]
@vaalvarezc sugiere usar el color #DAA520 en el modulo de la comparación de valores entre gastos e ingresos.

**Comment by miguelramirez93** [comment]
Se ajusta color egresos en componente comprobacion a #DAA520

**Comment by miguelramirez93** [comment]
PR -> https://github.com/udistrital/presupuesto_cliente/pull/286

**Comment by Soulfilip-UD** [comment]
Lune 16 Diciembre .
Se revisa y se cuenta con todos los ajustes menos uno, al filtrar Área Funcional por caracteres no encuentra resultados. Se intentara solucionar con la estrategia de un autocompletado .

Casi lista para cerrar la tarea

**Comment by miguelramirez93** [comment]
PR https://github.com/udistrital/presupuesto_cliente/pull/313

**Comment by Soulfilip-UD** [comment]
Queda por revisar el filtro en la columna de área funcional, cambio que se revisara en la reunión del 23 de Diciembre

**Comment by Soulfilip-UD** [comment]
Ajustes realizados 

Tarea finalizada
Proceeding to close Issue 👾
