### ISSUE TITLE
Ajustes Hito 2 Certificado de Registro Presupuestal CRP

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#161]
Están pendientes los siguientes ajustes :wrench: : 

- [x] Integración de los tipos de documentos con Kronos (argo, agora, resoluciones) :memo: 

- [x] Integración consecutivos  :1234: 

- [x] Propagación de saldos :money_mouth_face: 

- [x] Expedición de CRP

- [x] Integrar nuevo servicio para traer la informacion de necesidades_crud

**Comment by macaguegi** [comment]
Se realiza la integración de los consecutivos para solicitudes de CRP y CRP en el MID [PR MID](https://github.com/udistrital/plan_cuentas_mid/pull/76)

**Comment by macaguegi** [comment]
Al día 18/Noviembre quedan pendientes lo siguientes ajustes:

- [ ] Tabla de Solicitudes de CRP y de CRP debe mostrar si es de Inversión / Funcionamiento
- [ ] Tabla de Solicitudes de CRP y de CRP debe mostrar el nombre del Centro Gestor y la Entidad (Por ahora se están mostrando los IDs)
- [ ] Tabla de CRP debe mostrar el nombre del estado del Certificado de Registro Presupuestal
- [ ] En la visualización del detalle de Solicitudes y CRPs se debe mostrar el nombre de las metas y actividades **JBPM**
- [ ] En el formulario de registro de una solicitud de CRP se debe alinear a la derecha y poner notación de moneda a el campo "monto parcial"

- [ ] Las afectaciones a los saldos quedan pendientes y se realizarán de la mano de las afectaciones de los CDPs

Estado de la tarea : 70%. Se solicita revisión de líder técnico @Soulfilip-UD  para reunión de Noviembre 19 :octocat:

**Comment by macaguegi** [comment]
Día 26 de Noviembre : Estado de la tarea 60%

**Comment by macaguegi** [comment]
Se solicita a líder técnico @Soulfilip-UD la gestión de datos de prueba con el equipo de ARGO(para que coincidan con los datos de necesidades y de CDP) y registrar de manera exitosa Solicitudes de CRP.

**Comment by DianaPatriciaRamirez** [comment]
Las observaciones del 29 de noviembre son:

- [ ] Centro gestor debe mostrar el texto del área funcional. @macaguegi 

- [ ] Ajustar formato: Fecha de solicitud. Ejemplo: DD/MM/AAAA, 11/11/2019. @macaguegi 

- [ ] Falta registrar el documento presupuestal, dónde se muestran todos los CRPs expedidos. Con esta tarea se puede ver la propagación de saldos y las afectaciones. @juancsr 

- [ ] Falta "Fecha final vigencia CRP" con la cual se pueden verificar los pasivos y las reservas. @CarlosGutierrezArdila 

El próximo viernes 6 de diciembre se revisará.

**Comment by macaguegi** [comment]
Se realizan los ajustes solicitados , se habilitan los filtros en las tablas y también se pone el contenido del módulo en una nb-card tal como lo realizó el Ing. @davidmm07  en Fuentes de Financiamiento 

![image](https://user-images.githubusercontent.com/12780939/69926147-5b1a2c00-1481-11ea-9815-03ee35c67f9b.png)

La fecha de solicitud quedó con el formato DD/MM/AAAA

![image](https://user-images.githubusercontent.com/12780939/69926221-9caad700-1481-11ea-8f92-9d1ffb5f006f.png)

Se solicita la revisión por parte de líder técnico @Soulfilip-UD y de los compañeros @juancsr  y @CarlosGutierrezArdila  que continúan con otras funcionalidades del mismo módulo.  ✌️

**Comment by DianaPatriciaRamirez** [comment]
De acuerdo a revisión del 4 de diciembre, hace falta desarrollar:

- [ ] Propagación de saldos.

- [ ] Las afectaciones a los saldos quedan pendientes y se realizarán de la mano de las afectaciones de los CDPs

- [ ] Centro gestor debe mostrar el texto del área funcional.

- [ ] Falta registrar el documento presupuestal, dónde se muestran todos los CRPs expedidos. Con esta tarea se puede ver la propagación de saldos y las afectaciones.

- [ ] Falta "Fecha final vigencia CRP" con la cual se pueden verificar los pasivos y las reservas.

- [ ] Anulaciones parcial y total @miguelramirez93 

Se revisará nuevamente el viernes 6 de diciembre.

**Comment by DianaPatriciaRamirez** [comment]
En reunión del 6 de diciembre se observa lo siguiente para ser ajustado: 

- [ ] Organizar el menú, para que gestión de CRP aparezca de primeras.

- [ ] Al seleccionar el monto total del CRP, debe mostrar el valor "total" del CDP.

- [ ] Cambiar titulo de "Valor parcial" por "Valor".

- [ ] Corregir mensaje al guardar CRP, debido a que sale "Solicitud de CDP Registrada", cambiar por "Solicitud de CRP Registrada".

- [ ] Falta "Fecha inicio vigencia CRP".

- [ ] En Solicitud de Certificado de Registro Presupuestal, debería mostrar el valor de los rubros del CDP el cual va a ser afectado.

- [ ] Cambiar "CRP.centro-gestor" por "Area Funcional".

- [ ] Al ver el "Detalle de Solicitud de Certificado de Registro Presupuestal", se está cortando la información de la fuente, en los casos que tiene varias fuentes.

- [ ] Revisar lista de CRP expedidos.

se revisará avances el martes 10 de diciembre y finalizado el viernes 13 de diciembre.

**Comment by Soulfilip-UD** [comment]
- [ ] Se debe mostrar en la vista detalle del CDP un histórico de los movimientos asociados al CDP: CRP expedidos a partir de este.  (Consecutivo / fecha expedición / valor )

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 20 de diciembre, queda pendiente lo siguiente:

- [ ] Colocar el nombre del rubro tanto en "Información del CDP" e "Información para expedir CRP".

**Comment by Soulfilip-UD** [comment]
Se revisara los cambios en la reunión del viernes 23 Diciembre

**Comment by DianaPatriciaRamirez** [comment]
- [ ] Solo falta ajustar valores a la derecha.

**Comment by Soulfilip-UD** [comment]
Tarea Finalizada, gracias @juancsr 

Proceeding to close Issue 👾
