### ISSUE TITLE
Agregar helper para servicio del plan_adquisición

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#162]
- [x] Traer servicio que muestre las fuentes, metas, actividades y/o dependencias para la vigencia y el rubro actual.
- [x] Mostrar la Consulta de dicho servicio

**Comment by davidmm07** [comment]
a revisión @Soulfilip-UD

**Comment by davidmm07** [comment]
![image](https://user-images.githubusercontent.com/15944053/69092038-8c264580-0a19-11ea-8090-8c21547033b6.png)

**Comment by Soulfilip-UD** [comment]
Perfecto, tarea realizada y revisada en el entorno de test


Proceeding to close Issue 👾
