### ISSUE TITLE
Ajustes hito 2 Certificado de disponibilidad presupuestal

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_cliente#165]
Ajustes hito 2 Certificado de disponibilidad presupuestal

- [x]  Ajustes de servicios de necesidades

- [x]  Visualización de solicitud Y CDP

- [x]  Expedición de CDP 

- [x]  Simulación de consecutivos

- [x]  propagación de saldos (comprometidos)

**Comment by juancsr** [comment]
La continuación de la tarea se lleva en https://github.com/udistrital/presupuesto_cliente/issues/174

**Comment by Soulfilip-UD** [comment]
Continuar con el Issue #174 

Todo OK  por aquí

Proceeding to close Issue 👾
