### ISSUE TITLE
Ajustar Cliente - Todos los modulos de plan de cuentas se pueda manejar desde una misma vista  

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#17]
De acuerdo a los nuevos mockups adapatar een el cliente las vistas con todos los modulos. Tiempo estimado 6 horas con flexibilidad

**Comment by mcguegi** [comment]
Se integran las vistas de Rubros y Apropiaciones en **Gestión de Plan de Cuentas** .

**Comment by Soulfilip-UD** [comment]
Cambios realizados y revisados, tarea Finalizada. Proceeding to close Issue :space_invader:
