### ISSUE TITLE
Ajustes CDP

### ISSUE THREAD

**Issue by DianaPatriciaRamirez** [udistrital/presupuesto_cliente#174]
De acuerdo a revisión del 15 de noviembre, surgen las siguientes observaciones, se revisará nuevamente el 22 de noviembre y se espera un avance del 100%.

Historias de usuario:
- [49 a 50 ](https://drive.google.com/open?id=17_TqNLfjc7N1HUJSeSoGMZeXo5xejrtm1PoSmiYB-mo)
- [30 a 32](https://drive.google.com/open?id=1iDCadTaLxnifXubL6eo1wKUa2JpNaKjyg7hpwXU-Tro)
- [25 a 27](https://drive.google.com/open?id=1gEs0NjzxiqVq6w8PF4rl0eENydMEvNWqBKK4Wo27Uko)

- [x] El botón "Regresar" se debe colocar en la parte superior de la pantalla.
- [x] En "Detalle del CDP", para el campo "Área funcional" debe mostrar el nombre. Así mismo, se debe cambiar códigos por nombres en donde se requiera (Ejemplo: Dependencia Solicitante, metas, actividades, fuentes, etc.).
- [x] Agregar columna de "Tipo de Financiación" para poder consultar.
- [x] Distribuir los espacios de Fuentes y Actividades. (No cortar la información en cada campo)
- [x] Organizar el menú principal para que "Gestión de CDP" se encuentre antes que "Gestión de CRP".
- [x] Propagación de saldos.
- [x] Estados. (Falta mostrar estado anulado en CDP)
- [x] Afectaciones de CDP, incluyendo anulaciones total y parcial. (Falta anualción total)
- [x] Consultas (Revisar columnas, filtros y consultas de las HU de solicitud de CDP y CDP).

**Comment by juancsr** [comment]
**Hoy 27 de noviembre surgen las siguientes observaciones del modulo:**

- [ ] No se visualiza por completo la información de los CDP de Inversión en test

- [ ] La columna centro gestor está repetida

- [ ] Agregar columna Area funcional

- [ ] Agregar filtros correspondientes dados en la HU 26

- [ ] Revisar filtros de las columnas en solicitud de CDP

- [ ] Falta lista de CDP expedidos.

- [ ] Revisar que se listen los CDP generados por los movimientos de traslados y suspensión en lista de CDP expedidos.

**Se estima tener corregidas las observaciones y finalizado el modulo del martes 3 de diciembre**

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 3 de diciembre, se recomienda lo siguiente:

- [ ] Cambiar "Entidad" por "Centro Gestor".

**Comment by DianaPatriciaRamirez** [comment]
Se revisará nuevamente el martes 10 de diciembre.

**Comment by juancsr** [comment]
- [ ] Cambiar entidad por centro gestor en detalle CDP tanto en solicitud de CDP como CDP expedido.

- [ ] Cambiar responsable en solicitud CDP por el ordenador de gasto de la necesidad.

- [ ] Ajustar mostrar tipo de modificación presupuestal en detalle CDP de modificación presupuestal GLOBAL.cdp_modificacion.

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 13 de diciembre, quedan las siguiente observaciones:

- [ ] Para la solicitud de CDP, dejar el cargo del responsable "Ordenador del gasto".

- [ ] Dejar en negrita todos los titulos.

- [ ] Revisar la consulta de "Lista certificados de disponibilidad presupuestal".No se dejan quitar los filtros para volver a consultar.

Se revisará al 100% el martes 17 de diciembre.

**Comment by Soulfilip-UD** [comment]
- [ ] Columna objeto en negrita.

- [ ] Actualizar titulo de columna Valor actual por Saldo CDP en CDP expedido.

**Comment by Soulfilip-UD** [comment]
Se planea revisarse para la reunión del 23 de Diciembre

**Comment by Soulfilip-UD** [comment]
En la reunión se visualizo que los campos de CDP que contenia valores monetarios no estaban alineados a la derecha.
Lo cual se soluciono en el PR #331  esa misma tarde y todo queda OK

Tarea Finalizada 
Proceeding to close Issue 👾
