### ISSUE TITLE
Ajustar Mockups - Todos los modulos de plan de cuentas se pueda manejar desde una misma vista  

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#18]
Tras socializar los mockups con el Arquitecto, se sugirio agrupar en una misma vista todas las acciones referentes al plan de cuentas, por lo que se deben adapatar los mockups

**Comment by mcguegi** [comment]
Se hace una revisión de la herramienta Google App Maker para los mockups. Sin embargo , se observan algunas dificultades para generar los mockups . Por lo tanto, se socializa el tema con el líder técnico @Soulfilip-UD  para mirar si existe otra herramienta alternativa.

**Comment by mcguegi** [comment]
Se adjunta ZIP con los mockups generados en la herramienta draw.io 
[MockupsPlanCuentas.zip](https://github.com/udistrital/presupuesto_cliente/files/3315870/MockupsPlanCuentas.zip)

Se añade enlace para la previsualización de los mismos
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&page-id=8ORgLYlYZUCQ9LNISv3A#G1nBwIdN-Iue5I164bOOjwuNPBYWJMcBPB

**Comment by Soulfilip-UD** [comment]
El link tiene un inconveniente de tiempo de caducidad, más un excelente recurso. Elementos revisados y se anexaran al repositorio de documentación. Tarea finalizada. Proceeding to close Issue 👾
