### ISSUE TITLE
Consulta de rubros por fuente por vigencia

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#194]
Realizar una vista consulta por fuente de los rubros en los que se distribuyo, por vigencia asociado al Issue #148

**Comment by Soulfilip-UD** [comment]
- [ ] Distribuir en tareas y realizar el SCRUM poker

**Comment by davidmm07** [comment]
Se deja evidencia, y queda PR
![image](https://user-images.githubusercontent.com/15944053/69763657-df944400-113b-11ea-8695-3483f6fbbad5.png)

![image](https://user-images.githubusercontent.com/15944053/69763684-faff4f00-113b-11ea-8674-a022cd0df517.png)

**Comment by davidmm07** [comment]
A revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Se revisan los ajustes en la reunión del Martes 3 Diciembre a las 10 am

**Comment by davidmm07** [comment]
A revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Cambios revisados y desplegados en Test, Todo OK! 👍 

Tarea finalizada 
Proceeding to close Issue 👾
