### ISSUE TITLE
Funcionalidad asignar una apropiación a un rubro nuevo durante la vigencia actual

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#195]
Funcionalidad asignar una apropiación a un rubro nuevo durante la vigencia actual, Issue #128

**Comment by miguelramirez93** [comment]
PR https://github.com/udistrital/plan_cuentas_mongo_crud/pull/159

**Comment by miguelramirez93** [comment]
PR https://github.com/udistrital/presupuesto_cliente/pull/196

**Comment by Soulfilip-UD** [comment]
Revisada y validada en la app desplegada en Test. Todo OK!!
Tarea finalizada

Proceeding to close Issue 👾
