### ISSUE TITLE
Inicio de Vigencia HU 48

### ISSUE THREAD

**Issue by NeiderFajardo** [udistrital/presupuesto_cliente#239]
- [x] Realizar las vistas para crear una nueva vigencia y para consultar las vigencias existentes.

- [x]  Validar modelo de datos Vigencia.

- [x] Construir los servicios para registrar nueva vigencia.

- [x] Crear item en el menú para acceder a la gestión de vigencias.

- [x] Revisar y realizar anotaciones sobre las HU

**Comment by NeiderFajardo** [comment]
Modelo de datos actual en la base de datos de mongo.
![image](https://user-images.githubusercontent.com/22989456/70542833-6d5a3100-1b37-11ea-9834-cbe29f4d7d5d.png)


propuesta modelo de datos ajustado

![image](https://user-images.githubusercontent.com/22989456/70552685-d8136880-1b47-11ea-94a4-abe98b714683.png)

**Comment by NeiderFajardo** [comment]
Se hace la documentación de la nueva estructura de las vigencias y los mockups para las vistas que intervienen en la creación y al momento de listar las vigencias para ver su detalle.

**Comment by NeiderFajardo** [comment]
- [ ] Realizar una colección para las vigencias de área funcional y para el centro gestor.
- [ ] Agregar campo 'activo' en el modelo de datos y en el registro 'estado'.

**Comment by NeiderFajardo** [comment]
Se decide crear una colección por cada área funcional, donde en el nombre de la colección se haga uso de los códigos tanto del centro gestor como del área funcional, de esta forma, un ejemplo para los nombres de las colecciones sería el siguiente:

- vigencia_233_1

![image](https://user-images.githubusercontent.com/22989456/71019514-719ec500-20c8-11ea-84f3-6196df9127f2.png)


En donde 233 hace referencia al código del centro gestor y el 1 hace referencia al área funcional a la que la vigencia pertenece.

Los atributos de cada uno de los registros quedarán de la siguiente forma:

![image](https://user-images.githubusercontent.com/22989456/71019345-30a6b080-20c8-11ea-9879-339d65895398.png)

Teniendo en cuenta que el id de cada registro se obtiene del valor de la vigencia para que no se generen inconsitencias.

**Comment by DianaPatriciaRamirez** [comment]
Modelo de datos de inicio de vigencia listo para revisión de arquitectos, DBA y líder técnico. @Soulfilip-UD @corio27 @jairolh @fnrojash

**Comment by nodier25** [comment]
Se valida el modelo de bases de datos esta ok

**Comment by corio27** [comment]
Validado

**Comment by jairolh** [comment]
Se verifica ajustes según sugerencias. OK

**Comment by Soulfilip-UD** [comment]
- [ ]  Los estados de las vigencias on : actual, futura y cerrada

- [ ] Columna : Vigencia área funcional y nombre
<img width="162" alt="Screen Shot 2019-12-20 at 9 57 07 AM" src="https://user-images.githubusercontent.com/50924615/71264596-6dfe7e80-2312-11ea-9996-4a1860b52f7d.png">

- [ ] No hay vista detalle pero en la consulta general están todos los campos como columnas

**Comment by Soulfilip-UD** [comment]
- [ ] En la tabla de vigencias lanzar el cierre de vigencia como una acción

- [ ] Y a las vigencias cerradas lanzar la acción del resumen del cierre de vigencia

**Comment by Soulfilip-UD** [comment]
Ajustes realizados

Tarea finalizada
Proceeding to close Issue 👾
