### ISSUE TITLE
Desarrollo aprobacion pre-asignación inicial (cliente) boton - 5 horas - David

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#24]
- [x] Crear proceso qué llame el servicio de aprobacion masiva

**Comment by davidmm07** [comment]
Este servicio depende de del issue #21 y del issue del api_mongo: https://github.com/udistrital/plan_cuentas_mongo_crud/issues/72

**Comment by Soulfilip-UD** [comment]
Tarea realizada y revisada, también se revisada la calidad del código y OK

Al día de hoy se nota que se debe modificar la ubicación del boton para evitar confundir al usuaio, la tarea la realiza @juancsr  en el Issue #49 

Tarea lista para ser cerrada

**Comment by Soulfilip-UD** [comment]
Proceeding to close Issue 👾
