### ISSUE TITLE
Creacion de vista de cierre de vigencias 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_cliente#245]
- [x] creación y evaluacion de mockups con analista. Sólo has un borrador en una hoja pero no le inviertas mas de 2 horas a esta actividad.
- [x] implementacion de vista cierre anual

**Comment by CarlosGutierrezArdila** [comment]
Creada la funcionalidad y el formulario para ver información de precierre avance 80% con la información levantada existente

**Comment by Soulfilip-UD** [comment]
- [ ] Título ventana

<img width="329" alt="Screen Shot 2019-12-20 at 9 59 54 AM" src="https://user-images.githubusercontent.com/50924615/71263266-933dbd80-230f-11ea-9642-13fbae9c97a6.png">

- [ ] Título bóton
<img width="222" alt="Screen Shot 2019-12-20 at 10 01 07 AM" src="https://user-images.githubusercontent.com/50924615/71263328-ad779b80-230f-11ea-9c94-c7a94aafb6d5.png">

**Comment by Soulfilip-UD** [comment]
- [ ] Vigencia: 12/31/01 ----  Actualmente al querer hacer el cierre y aparece el año 01

**Comment by DianaPatriciaRamirez** [comment]
Solo falta: 

- [ ] En cierre de vigencia, en la vista de "Resumen ejecución presupuestal", al visualizar los pasivos exigibles debe enviar a la lista de CRP, en la vigencia que corresponde.

**Comment by Soulfilip-UD** [comment]
Tareas que corresponden a @CarlosGutierrezArdila  completadas al 100%

El item que hace falta sera realizado por @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Se ha realizado avances en el PR #375 mas no se ha combinado con la rama dev ya que en local tengo unos errores y debo corregirlos primero.

La ruta de las url para fuentes queda:

fuentes/{vigencia}/{codigo_fuente}
cdp/{vigencia}/{id_cdp}

Porcentajje de la tarea de @Soulfilip-UD  en un 80%

**Comment by Soulfilip-UD** [comment]
Desde la vista de vigencia se puede seleccionar la fuente de financiamiento y nos lleva directamente al detalle de esta, y al seleccionar los CRP nos lleva a la lista de CRP en la vigencia seleccionada.


Tarea finalizada
Proceeding to close Issue 👾
