### ISSUE TITLE
Anulación de CDP y RP - modificaciones

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#262]
Se requiere poder realizar la anulación de un CDP y RP para reversar el dinero.

**Comment by miguelramirez93** [comment]
```javascript
<ngx-anulacion-documento *ngIf="cambiotab" [vigencia]="2019" [centroGestor]="1" [documentData]="cdp" [movTypeToCreate]="'anul_cdp'" [modIdType]="'8'" (saved)="onSaved($event)"></ngx-anulacion-documento>
```

Se realizó un componente generico con el objetivo de manejar las anulaciones de CDP y CRP. Este componente es alimentado por:
INPUTS:
    *vigencia -> vigencia del documento que se desea anular.
    *centroGestor -> centro gestor del documento que se desea anular
    *documentData -> objeto con los datos del documento presupuestal que se registra en la db.
    *movTypeToCreate -> string con el nombre del movimiento que representa la anulación en lo parametros de la afectación. para el caso de los cdp es anul_cdp y para rp anul_rp.
    *modIdType -> id del tipo de movimiento registrado en movimientos_crud, ej: id para cdp -> 8. 
OUTPUTS:
    *saved -> emision de un dato booleano cuando se registra la anulación. util si se desea comunicar a un componente padre el registro exitoso de una anulación.

**Comment by miguelramirez93** [comment]
PR's:
-> https://github.com/udistrital/plan_cuentas_mongo_crud/pull/195
-> https://github.com/udistrital/plan_cuentas_mid/pull/122
-> https://github.com/udistrital/presupuesto_cliente/pull/286

**Comment by Soulfilip-UD** [comment]
- [ ] Al registrar una anulación no esta refrescando los datos, toca recargar manualmente para revisar

- [ ] Se debe mostrar el histórico de los movimientos asociados al CDP: anulaciones

- [ ] Y linkear por url el CRP

- [ ] La acción de anular un CDP se dispara desde la vista detalle del CDP y validar que solo se pueda realizar con CDP que parten de una necesidad

- [ ] Al realizar anulaciones parciales hasta completar una anulación total , debe quedar como una anulación total . Actualmente queda como Totalmente comprometido

**Comment by miguelramirez93** [comment]
PR https://github.com/udistrital/plan_cuentas_mongo_crud/pull/203

**Comment by miguelramirez93** [comment]
PR https://github.com/udistrital/presupuesto_cliente/pull/313

**Comment by Soulfilip-UD** [comment]
Se revisara los ajustes en la reunión del lunes 23 de Diciembre

**Comment by Soulfilip-UD** [comment]
- [ ] Al crear varias modificaciones a la vez se debe separar los consecutivos generados por un coma

- [ ] En la vista detalle del CDP suspensión quitar la columna CDP

**Comment by Soulfilip-UD** [comment]
Al día 3 de enero :

- [ ] Queda por realizar la navegación por url de los CDP , tarea realizada por @Soulfilip-UD 

- [ ] Revisar la anulación quedo en el detalle del CDP (caso : CDP que pasrten de una necesidad)

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 8 de enero, se observa lo siguiente:

- [ ] Falta realizar la navegación por url de los CDP , tarea realizada por @Soulfilip-UD que Felipe se compromete entregarla este viernes 10 de enero.
- [ ] No se observa ningún avance de anulación de CRP, de acuerdo historia de usuario [HU - 40 A 42 - Anulacion Total y Parcial de Reservas V3](https://drive.google.com/open?id=1KtBll3BwQrJiiUd24AZruAUpoHvCa8uko1WQtM4utsE) Queda el compromiso por parte del líder técnico de revisar lo desarrollado, desplegarlo y presentar totalmente finalizado este issue para el viernes 10 de enero.

**Comment by Soulfilip-UD** [comment]
El desarrollador @miguelramirez93 se compromete a entregar un avance sino el definitivo del desarrollo de anuulación de CRP que hace falta.

La tarea de navegación por URL de @Soulfilip-UD  esta en un 80% y el avance queda en el PR #375 , se logra manejar por url:
La ruta de las url para fuentes queda:

fuentes/{vigencia}/{codigo_fuente}
cdp/{vigencia}/{id_cdp}

**Comment by DianaPatriciaRamirez** [comment]
El próximo martes 21 de enero se revisarán los avances de este desarrollo.

**Comment by miguelramirez93** [comment]
se añade interface para anulación en menú de CRP

![image](https://user-images.githubusercontent.com/17803254/72741332-6c281500-3b75-11ea-9b00-97ce084d9f6b.png)

**Comment by miguelramirez93** [comment]
tipos de anulaciones (parcial y total)
![image](https://user-images.githubusercontent.com/17803254/72741455-adb8c000-3b75-11ea-8b56-abf1cb0c9842.png)

**Comment by miguelramirez93** [comment]
registro de la anulación 
![image](https://user-images.githubusercontent.com/17803254/72741538-d8a31400-3b75-11ea-8bb5-bc84218f0a1c.png)

**Comment by miguelramirez93** [comment]
Listado de anulacipnes hechas desde interface de crp

![image](https://user-images.githubusercontent.com/17803254/72741595-f6707900-3b75-11ea-8254-61ad5fbcc170.png)

**Comment by Soulfilip-UD** [comment]
Issue documentado y funcionalidad funcionando en test sin dificultades. 

Tarea finalizada
Proceeding to close Issue 👾
