### ISSUE TITLE
Registrar CRP como documento presupuestal

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#278]
Al expedir un CRP se debe tener en cuenta:

- [x] movimientos presupuestales de saldo ejecutado

- [x] registrarlo como documento presupuestal

- [x] Incluir fecha de fin de vigencia del CRP

**Comment by juancsr** [comment]
> Al expedir un CRP se debe tener en cuenta:
> 
> * [ ]  movimientos presupuestales de saldo ejecutado

No entiendo a qué se refiere con esto. @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Ajustes a revisar en la reunión del 23 de Diciembre

**Comment by Soulfilip-UD** [comment]
> > Al expedir un CRP se debe tener en cuenta:
> > 
> > * [ ]   movimientos presupuestales de saldo ejecutado
> 
> No entiendo a qué se refiere con esto. @Soulfilip-UD

Una confusión en el momento, que referia a CRP que partian del CDP de un movimiento. Lo cual no es posible

**Comment by Soulfilip-UD** [comment]
Ajustes realizados

Tarea finalizada
Proceeding to close Issue 👾
