### ISSUE TITLE
Crear y actualizar repositorio a ultima versión estable del proyecto cliente

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#3]
- [x]  Crear repositorio para el nuevo cliente de Kronos

- [x] Identificar y actualizar las diferentes librerias del cliente

- [x] Solucionar conflictos de las mismas dependencias al actualizar versión.

**Comment by davidmm07** [comment]
Se actualizan las diferentes dependencias en los siguientes commits:
#2 #1

**Comment by davidmm07** [comment]
Se realizan los siguientes cambios antes de la actualización:

https://github.com/udistrital/financiera_cliente_new/commit/da3cf07c63b3a28b28cc6814f51cb21aa7f60b93

Se corrigen se corrigen importaciones de estilos breakpoint, variable de autenticación y se actualizan librerias:

https://github.com/udistrital/financiera_cliente_new/commit/9484af84a04715987bc514675dfbca805e34c6e3

Actualización a versión de angular_7:
https://github.com/udistrital/financiera_cliente_new/commit/ed738f4ecc76887470ac1b63a1156197f27337e6

**Comment by miguelramirez93** [comment]
Revisado , solo se deja la observacion de referenciar el issue en el comentario del commit para no hacer doble trabajo.
