### ISSUE TITLE
Menu global kronos (presupuesto, contabilidad, reportes, tesoreria)

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#327]
Se requiere un menu global en el que se puedan ir desglozando las diferentes vistas por subsistema, teniendo en mente que cada subsistema es un cliente separado

**Comment by Soulfilip-UD** [comment]
El menu se requiere modificar desde el cliente de configuración en el host:

http://pruebasconfiguracion.portaloas.udistrital.edu.co/

Ya que se requiere editar el menu, se deberia encontrar el rol o la aplicación mediante los filtros, mas por alguna razón no aparaece la aplicación `presupuesto_kronos` ni el rol `ADMIN_PRESUPUESTO `:
<img width="1054" alt="Screen Shot 2019-12-24 at 3 03 31 AM" src="https://user-images.githubusercontent.com/50924615/71402103-00946b80-25fa-11ea-9ce8-7d820a1f5102.png">
![Uploading Screen Shot 2019-12-24 at 3.03.12 AM.png…]()

**Comment by Soulfilip-UD** [comment]
Al ingresar a la base de datos , se evidencia que hay 2 registro asignados al rol `ADMIN_PRESUPUESTO`, razón por la cual puede estar sucendiendo el error de no verlo en el cliente.
<img width="347" alt="Screen Shot 2019-12-24 at 1 08 42 AM" src="https://user-images.githubusercontent.com/50924615/71402246-5cf78b00-25fa-11ea-895e-2e81c460a32f.png">

Posteriormente de organizar las opciones de menu ya registradas, se ingresaron las nuevas opciones apuntando directamente al API 
<img width="726" alt="Screen Shot 2019-12-24 at 3 07 04 AM" src="https://user-images.githubusercontent.com/50924615/71402345-97612800-25fa-11ea-9979-615457b2df70.png">
<img width="668" alt="Screen Shot 2019-12-24 at 3 07 50 AM" src="https://user-images.githubusercontent.com/50924615/71402363-9d570900-25fa-11ea-89ec-afaed48be4a6.png">

Mas al intentar registrar la asociación de un menu a un rol, hay un error en el servicio.
<img width="668" alt="Screen Shot 2019-12-24 at 3 07 50 AM" src="https://user-images.githubusercontent.com/50924615/71402443-de4f1d80-25fa-11ea-8704-7bff6670134f.png">
<img width="263" alt="Screen Shot 2019-12-24 at 3 09 51 AM" src="https://user-images.githubusercontent.com/50924615/71402452-e5762b80-25fa-11ea-852c-18525c4d7aaf.png">

Y el error que registra CLoudwatch es :
<img width="821" alt="Screen Shot 2019-12-24 at 2 55 50 AM" src="https://user-images.githubusercontent.com/50924615/71402473-f7f06500-25fa-11ea-8df5-7199a6895ece.png">

**Comment by Soulfilip-UD** [comment]
Al no poder ealizar la asoción la tarea no se puede finalizar a tiempo, ya me comunique con @fabianLeon  quien revisara el comportamiento del cliente como del API tras pronto pueda.

**Comment by fabianLeon** [comment]
Se resuelve issue cableando correctamente servicio en wso2 y removiendo flujo de google hasta que esté estable.

**Comment by Soulfilip-UD** [comment]
Ya que el equipo del core ofrece un panel para saltar en los distintos sistemas y/o sub-sistemas a los que este asociado el usuario, no se requiere un menu global sino que cada susbsitema es configurado como una aplicación única, por lo que tiene un menu propio.

Por lo que el menú de presupuesto no se modifica, y se adjunta las opciones para el menu de contabilidad.

<img width="358" alt="Screen Shot 2020-01-09 at 3 54 20 PM" src="https://user-images.githubusercontent.com/50924615/72103966-522a3f00-32f8-11ea-85e6-21a3cf220e4d.png">

<img width="1031" alt="Screen Shot 2020-01-09 at 3 52 55 PM" src="https://user-images.githubusercontent.com/50924615/72104073-96b5da80-32f8-11ea-859e-0b8af0bebd08.png">


Falta realizar las traducciones en el sistema de estas opciones de menú, tarea en un 90% .

**Comment by Soulfilip-UD** [comment]
<img width="237" alt="Screen Shot 2020-01-10 at 12 54 38 AM" src="https://user-images.githubusercontent.com/50924615/72129322-ce963f80-3343-11ea-8694-fb89b19dc809.png">


Proceeding to close Issue 👾

**Comment by DianaPatriciaRamirez** [comment]
Ingeniero Felipe no cerrar issue hasta no terminar lo solicitado, falta: 

- [ ] Mockup del menú para los reportes del subsistema de presupuesto.

**Comment by Soulfilip-UD** [comment]
Se realiza el siguiente mockup, en el que se podran tener en un misma las opciones de los reportes que tiene acceso el usuario.
![mock_reportes-01](https://user-images.githubusercontent.com/50924615/72377858-42d33900-36de-11ea-8f7c-e0473b4dbb3e.png)

Para alimentar las opciones de reportes, se propone usar la misma aplicación de pruebasconfiguración, usando como:

aplicación: aplicación
nombre: nombre reporte
descripción: descripción reporte
url: label que se envia a spagobi
template: reporte
tipo_opción: botón

<img width="516" alt="Screen Shot 2020-01-14 at 2 57 42 PM" src="https://user-images.githubusercontent.com/50924615/72378081-b412ec00-36de-11ea-9844-49d1fe83807f.png">

**Comment by Soulfilip-UD** [comment]
Tarea Finalizada

Proceeding to close Issue 👾
