### ISSUE TITLE
Reporte ejecución de gastos e ingresos

### ISSUE THREAD

**Issue by juancsr** [udistrital/presupuesto_cliente#336]
Crear el reporte de ejecución de gastos e ingresos.
 **Documentación:** 
https://docs.google.com/document/d/1_ULRjMySxpviEOUkCRmFAc5K5gLU22QYuH7ODdNbgcw/edit

**Comment by juancsr** [comment]
Al realizar la conexión a MongoDB desde Knowage
http://intelligentia.udistrital.edu.co/knowage/servlet/AdapterHTTP?PAGE=LoginPage&NEW_SESSION=TRUE#

Se produce el siguiente error:
![image](https://user-images.githubusercontent.com/19156525/71490247-e1fbc380-27f7-11ea-9900-96a8f3e05e65.png)


En el kanban: https://tuleap.udistrital.edu.co/plugins/tracker/?aid=34300
se solicita  DBA que se les asigne los permisos pertinentes al usuario.

**Comment by juancsr** [comment]
![image](https://user-images.githubusercontent.com/19156525/71728487-365ffe00-2e0b-11ea-8b4e-a2d16dc64b23.png)

**Comment by juancsr** [comment]
70% de avance

**Comment by juancsr** [comment]
Se sube nueva versión del reporte y se ajusta el cliente para renderizar reportes de knowage en el issue #351 .

![image](https://user-images.githubusercontent.com/19156525/71984229-71d93e80-31f6-11ea-8943-b55a4d8417b7.png)

**Comment by juancsr** [comment]
Reporte completado.

**Comment by Soulfilip-UD** [comment]
Tarea Finalizada
Proceeding to close Issue 👾
