### ISSUE TITLE
Reporte Listado de Apropiaciones - Consecutivo de Disponibilidades

### ISSUE THREAD

**Issue by NeiderFajardo** [udistrital/presupuesto_cliente#345]
- [ ] Configurar entorno de trabajo Knowage Server y Knowage report designer.
- [ ] Construir reporte de listado de apropiaciones.
- [ ] Construir reporte de consecutivo de disponibilidades.

**Comment by NeiderFajardo** [comment]
Se realiza la configuración del servidor de knowage para que se conecte con la base de datos mongo de presupuesto. Se crea el query para consultar las vigencias proyectando solamente los valores que se necesitan en el reporte.

`var vigencia = $P{vigencia};
var area_funcional = $P{unidad_ejecutora};
var query = db.getCollection("arbol_rubro_apropiacion_"+vigencia+"_"+area_funcional).aggregate([
    {
        "$project": {
            "_id": 1,
            "nombre": "$nodorubro.general.nombre",
            "valor": "$valor_actual"
        }
    },
     { 
         "$sort": { 
  			"_id": -1
  		}
  	}
   ]);`

Se crean los parámetros de la vigencia y de área funcional por la que el ususario quiere consultar las apropiaciones.

**Comment by NeiderFajardo** [comment]
Se configura la aplicación Knowage report designer para construir los reportes, se procede a construir el reporte de apropiaciones iniciales con la información obtenida de la consulta hecha en el servidor. Falta agregar el encabezado de la plantilla definida por el grupo.

**Comment by NeiderFajardo** [comment]
Se carga el reporte en el servidor Knowage para que pueda ser embebido en el cliente presupuesto.
Se tiene dificultad para usar los parámetros necesarios dentro del reporte, se corrige este problema con ayuda del arquitecto Jhon, para dejar funcionando el reporte en el servidor.
Falta embeber el reporte dentro del cliente presupuesto.

**Comment by NeiderFajardo** [comment]
Se construye la plantilla para el reporte de consecutivo de disponibilidades, falta obtener datos y completar reporte.

**Comment by NeiderFajardo** [comment]
#370

**Comment by DianaPatriciaRamirez** [comment]
No se observa avances del reporte Consecutivo de Disponibilidades, por favor adjuntar avances, pantallazo del reporte y commits @NeiderFajardo

**Comment by NeiderFajardo** [comment]
Se agrega el reporte de "Consecutivo de Disponibilidades" a la vista del cliente de presupuesto, se realiza el pull request para agregarla a la rama dev, falta la aprobación por el lider técnico.

![image](https://user-images.githubusercontent.com/22989456/72305345-74e28d80-3641-11ea-8bf3-6e65eca6dcb0.png)

**Comment by Soulfilip-UD** [comment]
Tarea Realizada y revisada
Proceeding to close Issue 👾
