### ISSUE TITLE
Creación de reporte de consecutivo de compromisos (CRP)

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_cliente#348]
- [x] creacion de reporte de consecutivo de disponibilidad

**Comment by CarlosGutierrezArdila** [comment]
![image](https://user-images.githubusercontent.com/32855979/71730552-7e355400-2e10-11ea-8fc1-9253c787d8cc.png)
en la semana del 30 al 3 se trabajo en la elaboracion del reporte de consecutivo de compromisos, se parametriza por vigencia y area funcional.
![image](https://user-images.githubusercontent.com/32855979/71730684-ceacb180-2e10-11ea-9bfd-408335166046.png)
se avanzo en la informacion mostrada en la parte superior, falta incluir y mapear las columnas solicitadas en el análisis.
en el momento el avance de la tarea es del 60% ya que se tuvieron inconvenientes con la configuracion de la herramienta de reportes, a dia de hoy falta solucionar lo siguiente: 

- [ ] Realizar junto con los demás miembros del equipo la configuración del cliente para acceder a los reportes

- [ ] Realizar los cruces de datos adicionales para completar las columnas

- [ ] Corregir el flujo de los parametros de reportes  en knowage junto con los miembros del equipo de desarrollo

**Comment by CarlosGutierrezArdila** [comment]
se genera el reporte y se deja la version subida en la plataforma, tarea finalizada 100% 
![image](https://user-images.githubusercontent.com/32855979/72105733-1d1feb80-32fc-11ea-8c05-009d443add16.png)

**Comment by Soulfilip-UD** [comment]
Gracias muy buena documentación

Tarea finalizada
Proceeding to close Issue 👾
