### ISSUE TITLE
Reporte CDP

### ISSUE THREAD

**Issue by juancsr** [udistrital/presupuesto_cliente#363]
Reporte de CDP

**Comment by juancsr** [comment]
Avances:

![image](https://user-images.githubusercontent.com/19156525/72104485-86eac600-32f9-11ea-857d-7b803f19da8f.png)

![image](https://user-images.githubusercontent.com/19156525/72104509-9407b500-32f9-11ea-8e9e-1f52388ec6c5.png)

Total avance: 90%, falta mostrar el jefe de dependencia solicitante y el responsable de presupuesto.

**Comment by juancsr** [comment]
Reporte completado generado desde el cliente de kronos:
![image](https://user-images.githubusercontent.com/19156525/72124329-54a98a80-3332-11ea-8aaa-1afb1b6f7b5e.png)

![image](https://user-images.githubusercontent.com/19156525/72124341-5ffcb600-3332-11ea-946d-c7725fe8ca5b.png)

**Comment by Soulfilip-UD** [comment]
perfecto

Tarea realizada y revisada en test 
Para cargar el reporte se debe forzar el http, ya que el servicio de spagobi genera problemas de CORS

Proceeding to close Issue 👾
