### ISSUE TITLE
Reporte CRP

### ISSUE THREAD

**Issue by juancsr** [udistrital/presupuesto_cliente#364]
Reporte CRP

**Comment by juancsr** [comment]
Avances:
![image](https://user-images.githubusercontent.com/19156525/72105130-f0b79f80-32fa-11ea-8666-2ac574c14e0f.png)

![image](https://user-images.githubusercontent.com/19156525/72105316-57d55400-32fb-11ea-88f0-dafe67fc1c72.png)


Avance total: 50%

- Falta incluir tipo y número de compromiso
- Falta agregar modalidad de selección
- Falta incluir el jefe de presupuesto

**Comment by juancsr** [comment]
Reporte completado y generado desde el cliente de kronos:

![image](https://user-images.githubusercontent.com/19156525/72124408-a6eaab80-3332-11ea-86a1-a464e7d77e08.png)

![image](https://user-images.githubusercontent.com/19156525/72124432-ba961200-3332-11ea-9940-4960b3e4bf14.png)

**Comment by Soulfilip-UD** [comment]
perfecto

Tarea realizada y revisada en test
Para cargar el reporte se debe forzar el http, ya que el servicio de spagobi genera problemas de CORS

Proceeding to close Issue 👾
