### ISSUE TITLE
creación de reporte de disponibilidades comprometidas por rubro

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_cliente#365]
- [x] creación de reporte de disponibilidades comprometidas por rubro

**Comment by CarlosGutierrezArdila** [comment]
se genera el reporte y se deja la version subida en la plataforma, tarea finalizada 100% 
![image](https://user-images.githubusercontent.com/32855979/72105514-abe03880-32fb-11ea-97ed-ac293db93fb4.png)

**Comment by Soulfilip-UD** [comment]
Buen trabajo, el reporte se visualiza con los cambios que realizo @juancsr  en el Issue #351 

Tarea Realizada
Proceeding to close Issue 👾
