### ISSUE TITLE
Parámetros para reporte de CDP en kronos

### ISSUE THREAD

**Issue by juancsr** [udistrital/presupuesto_cliente#368]
Implementar parámetros necesarios para generar reporte de CDP creados desde kronos.

**Comment by juancsr** [comment]
Debido a que el reporte que se consume es un iframe de knowage, el SDK no tiene métodos para devolver únicamente el PDF. A demás, recomiendo utilizar el iframe de knowage, puesto que ya trae por defecto opciones como la impresión del documento y exportarlo a distintos formatos.

Aquí se puede apreciar el reporte generado con parámetros enviados desde la aplicación kronos:
![params](https://user-images.githubusercontent.com/19156525/72308701-f68ae900-364a-11ea-8315-73bd644f342e.gif)

Para evitar el problema del usuario, cuando se crea un reporte, se puede elegir si un parámetro se muestra o no. Entonces podemos dejar el parámetro usuario escondido y enviarlo en los parámetros desde la aplicación.

![image](https://user-images.githubusercontent.com/19156525/72308523-aca20300-364a-11ea-84fb-ede68d72032b.png)

El ejemplo se puede encontrar en:

**Comment by Soulfilip-UD** [comment]
La integración de los parametros del usuario se realizo correctamente por lo que la tarea fue realizada.

Proceeding to close Issue 👾
