### ISSUE TITLE
ajuste de filtro y suscripción a solicitud del filtro y tabla de la sección de crp

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/presupuesto_cliente#398]
se requiere ajuste en solicitudes de la vista de la tabla de crp ya que al realizarse algún cambio no se refresca la tabla y es necesario refrescar la vista

**Nota: Se permite la adición de Store de ser necesario (la prioridad es resolver el problema) }**

**Comment by ManuelMurillo** [comment]
Se realiza el ajuste para la actualizacion de la tabla de CRP's
