### ISSUE TITLE
ajustar archivo de variables de entorno de desarrollo

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/presupuesto_cliente#399]
realizar modificaciones en el archivo de variables de entorno par desarrollo en local para que no use las apis apuntando directamente a ellas ya que eso requiere vpn , en su ligar se debe apuntar a wso2, esto con el fin de facilitar el tiempo de desarrollo.

se permite basarse en el archivo de variables de despliegue en test.

si algún endpoint no responde al pasar por wso2 , informar ya que puede que no este actualizado allí o no tenga permisos el cliente

**Comment by ManuelMurillo** [comment]
Se ajustan los endpoints para usarse a travez del modulo de autenticacion:

- Necesidades_Crud
- Administrativa
- Administrativa_Pruebas
- Plan_Cuentas_Mongo
- Plan_Cuentas_Mid
- Movimientos_Crud
- Core

**Comment by ManuelMurillo** [comment]
Para la tabla de Solicitud de CDP, existe un problema en la peticion de los elementos, no se resuelve por tiempo de conexión agotado:

```
endpoint:

/necesidad
    ?limit=-1
    &fields=Id,TipoFinanciacionNecesidadId,ConsecutivoNecesidad
    &query=EstadoNecesidadId.CodigoAbreviacionn:CS
```

**Comment by BOTOOM** [comment]
se agradecería escribir el endpoint completo

**Comment by ManuelMurillo** [comment]
`'https://autenticacion.udistrital.edu.co/apioas/necesidades_crud/v1/'`

**Comment by BOTOOM** [comment]
se ajusta el error de esa petición y de otras que pueden ocasionar lo mismo
