### ISSUE TITLE
Generar mockup arbol de rubros 

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#4]
Diseñar y generar el mockup para la visualización del árbol de rubros que contempla los siguientes items
- [x] Mostrar el árbol de rubros
- [x] Ver la información de un rubro seleccionado
- [x] Añadir boton para Editar el rubro
- [x] Añadir boton para añadir un nodo hijo al rubro seleccionado

**Comment by macaguegi** [comment]
Se adjunta mockup de árbol de rubros
[Mockup](https://drive.google.com/file/d/1YoKiN7OEdrMylynRU0uUgJ0Zlc0M8hvT/view?usp=sharing)

**Comment by miguelramirez93** [comment]
Se revisa el mockup . Cumple con las caracteristicas solicitadas mejorando la usabilidad respecto a la version anterior.
