### ISSUE TITLE
ajustes visuales al cliente de presupuesto

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/presupuesto_cliente#402]
de a cuerdo al documento de pruebas realizado por la analista se requiere realizar ajustes visuales , al cliente de presupuesto en las secciones de:

- modificación de apropiación (opción de Apropiación).
- modificación de apropiación (opción de Fuentes de financiamiento ).

**Comment by dmarcela09** [comment]
Las imagenes acontinuacion muestran los cambios visuales para modificacion-apropiacion en el cliente de presupuesto, se modifican los botones "seleccionar" y "agregar" para reconocer su funcionalidad (antes no era posible identificar que eran botones), tambien se visualiza la pestaña de resumen de la modificacion y se da funcionalidad al boton "siguiente" para pasar a la etapa de 4 "Guardar".

![Botones "Seleccionar" y "Agregar"](https://user-images.githubusercontent.com/26507343/97055492-8780e000-154c-11eb-804d-e9e06b9d3151.JPG)
![Botones "Seleccionar" y "Agregar" activo](https://user-images.githubusercontent.com/26507343/97055496-88b20d00-154c-11eb-9f88-f2a48345487b.JPG)
![Funcionamiento boton "Siguiente" que redirije a al paso 4. Guardar: Resumen de la Modificacion](https://user-images.githubusercontent.com/26507343/97055497-88b20d00-154c-11eb-87bb-6125551563c3.JPG)

Adicinalmente, se arreglan los botones para la modificacion de fuentes, botones "seleccionar fuente" e "ingresar relacionado".

![Botones "Seleccionar fuente" e "Ingresar relacionado".](https://user-images.githubusercontent.com/26507343/97055712-fd854700-154c-11eb-8e4a-79af7a3af9a8.JPG)
