### ISSUE TITLE
revisión y manejo de errores en casos de no poder enviar u obtener data

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/presupuesto_cliente#403]
revisar peticiones y realizar manejo de errores al momento de enviar datos y de recibir datos en las secciones:

- modificación de apropiación.
- solicitud de cdp.

**Comment by dmarcela09** [comment]
Revision y manejo de errores: Error interno en el servidor
![Mensajes de error interno](https://user-images.githubusercontent.com/26507343/97061525-c4ed6980-155c-11eb-871b-e4b89250b581.png)
