### ISSUE TITLE
barra de progreso para arbol en presupuesto

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/presupuesto_cliente#430]
para la seccion de aprobación presupuestal es necesario crear una barra de carga para el arbol ya que se demora, la gracia no es que lo remplace , es que aparezca arriba del arbol, esto con el fin de darle al usuario un estado de la carga del arbol

**Comment by ManuelMurillo** [comment]
Existe un problema con los tiempos de carga que hacen muy dificil la conclusion de esta tarea, se analizo la situacion con el equipo de trabajo y se revisaron las tareas de ajuste de arbol de presupuesto, sin embargo por la construccion de la API se nos hace muy dificil seguir reduciendo los tiempos de carga. se sigue buscando solucion

**Comment by ManuelMurillo** [comment]
El problema con respecto a los tiempos de respuesta de los endpoints ya se soluciono para poder realizar los ajustes de la barra de carga
