### ISSUE TITLE
Identificar elementos parametrizables

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/presupuesto_cliente#436]
De la mano de @mcrubianot

**Comment by brayanpasa99** [comment]
Se hace una primera aproximación a los campos parametrizables de:

[Pruebas Presupuesto](https://pruebaspresupuesto.portaloas.udistrital.edu.co/)

La información se tiene en:

[Primer Documento de Parámetros](https://www.notion.so/brayanpasa99/Identificaci-n-de-Par-metros-Cliente-af2a82229d0e405caacddf869620a9f5)

Se va a realizar una socialización el día de mañana con María Claudia a las 8:30 AM

**Comment by brayanpasa99** [comment]
Después de socializar la información del cliente con María Claudia, se añade al documento una sección de campos que se había pasado por alto en la primera revisión, se agregan la sección de notas y de faltantes con las respectivas observaciones obtenidas en la reunión.

[Documento de Parámetros](https://www.notion.so/brayanpasa99/Identificaci-n-de-Par-metros-Cliente-af2a82229d0e405caacddf869620a9f5)

**Comment by AlexFBP** [comment]
Labor principal de este Issue, efectuada. Se cierra este Issue para continuar el desarrollo en #438
