### ISSUE TITLE
Clasificar Parámetros Explícitos/Implícitos

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/presupuesto_cliente#437]
Continúa #436

Una vez identificados los elementos parametrizables, clasificarlos según:
- Explícitos, que se ajustan desde el desarrollo
- Implícitos, que se consultan de otras APIs y/o son transversales

**Comment by brayanpasa99** [comment]
Se añade una columna a las tablas identificando el tipo de parámetro.

[Clasificación de parámetros](https://www.notion.so/brayanpasa99/Identificaci-n-de-Par-metros-Cliente-af2a82229d0e405caacddf869620a9f5)
