### ISSUE TITLE
Ajuste despliegue arbol de pre-apropiaciones

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#46]
- [x] Despliegue en ambiente de test.
- [x] Validar que la funcionalidad del arbol de preasignación inicial este correcta en dicho ambiente

**Comment by davidmm07** [comment]
Tarea se deja pendiente debido a  los problemas de despliegue del ambiente de desarrollo, queda pendiente hasta migrar lo desarrollado hasta el momento para el ambiente que se tiene actualmente planeado (pre-producción en amazon)

**Comment by Soulfilip-UD** [comment]
Hasta que la aplicación no este estable en el ambiente de test, no es posible revisar si se necesitan ajustes. 
La tarea continua

**Comment by davidmm07** [comment]
Se revisa creación de preasignación inicial y ya esta desplegando correctamente en la ruta 
https://pruebaspresupuesto.portaloas.udistrital.edu.co/#/pages/plan-cuentas/apropiaciones

Evidencia: 

![image](https://user-images.githubusercontent.com/15944053/64564245-adcac880-d316-11e9-9b28-4cfe82f78615.png)

**Comment by Soulfilip-UD** [comment]
Se revisa el despliegue y la versión cuenta con todo menos con los items del menu, más este error se refiere directamente con el funcionamiento de 'Configuraciones - proyecto del core' el cual está en fase de ajustes. El desarrollo esta finalizado y la tarea revisada

Proceeding to close Issue :space_invader:
