### ISSUE TITLE
Propagar valores de rubros

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/presupuesto_cliente#468]
## Consideraciones / Referencias
- [Sprint Review/Planning del 8 Nov 2021](https://drive.google.com/file/d/1AL4bZVmJ_CwuXcqn7_EoJTbZwnRdYGYn/view)
- Al aprobarse una necesidad por el jefe de dependencia es cuando debe descontarse el valor disponible del rubro
- Los valores disponibles del rubro presumiblemente tienen que registrarse en [movimientos_crud](https://github.com/udistrital/movimientos_crud)

## Tareas
- [x] Revisar y/o Ajustar funcionamiento de [movimientos_crud](https://github.com/udistrital/movimientos_crud)
- [x] Identificar API (MID? CRUD?) que debe realizar la "propagación" de valores
- [x] ~~Crear controlador que reciba la necesidad, la cual deberá consultar y cuyos valores debe propagar a la "ejecución presupuestal", "contabilidad de rubros" - Entre otros, deberá tomar el último registro guardado en movimientos~~ Revisar funcionamiento del controlador en movimientos_crud `registrar_multiple` para identificar posibles ajustes que permitan hacer "movimientos presupuestales", teniendo en cuenta los cálculos entre valores (pasados en la petición) y saldos
- [x] ~~Crear controlador que reverse la propagación de los valores de la necesidad, la cual deberá consultar y cuyos valores debe reversar a la "ejecución presupuestal", "contabilidad de rubros" - Entre otros, deberá tomar el último registro guardado en movimientos y crear un nuevo~~ (Si aplica) Hacer los ajustes pertinentes

@DanKazuky Para la parte de necesidades:

- [x] 1. Identificar a donde se va el "Aprobar Necesidad"
   - ~~Si es a un MID, continuar con el paso 3~~
   - ~~Si~~ Es a un CRUD...
- [x] 2. Hay que interceptar el envío al CRUD de necesidades. Seleccionar un MID adecuado, ojalá de los que ya tenga acceso el cliente de necesidades
    1. Crear el controlador que interceptaría la petición del punto 1
    2. Implementarlo, hacer que reciba tal cual la petición y la reenvíe con el mismo método que se le estaría enviando al CRUD
    3. Consumirlo, que desde el cliente se cambie el endpoint al que le apunta el "Aprobar Necesidad"
- [x] 3. Hacer el "movimiento presupuestal" que actualice las "cuentas presupuestales"
- [x] 4. Editar la vista de "Editar la necesidad" para que tenga en cuenta en los límites, ya no lo que viene por el plan de adquisiciones, sino los saldos de las "cuentas presupuestales"

**Comment by brayanpasa99** [comment]
## Análisis API de Movimientos

* Al parecer necesidades_cliente no tiene permisos para acceder al API de Movimientos

> Solución: Se espera que necesidades_cliente acceda a un MID y este a su vez al API de movimientos sin problema

* En este momento los tipos de movimiento con nombre: Adición, Reducción, Adición Fuente y Reducción Fuente se relacionan con movimientos a las Fuentes, se propone la creación de tipos de movimiento relacionados con metas, actividades y rubros.
* Se intuye que los parámetros de cada tipo de movimiento permitirán almacenar la relación entre RUbros, Fuentes, Metas y Actividades **(por confirmar)***

> Se resuelve realizar ciertas modificaciones al API de Movimientos con el fin de usarla en la propagación y actualización de valores buscada al aprobar la necesidad, se propone:
* Agregar campo de saldo en movimiento_detalle
* Agregar campo de metadatos en movimiento_proceso_externo
* Cambio del dominio de parametros en tipo_movimiento, de json a jsonb

**Comment by AlexFBP** [comment]
![image](https://user-images.githubusercontent.com/6588872/142954334-fc6e8585-ae29-4b7c-b5dd-28581f707b31.png)

**Comment by AlexFBP** [comment]
@DanKazuky Para la parte de necesidades:

- [ ] 1. Identificar a donde se va el "Aprobar Necesidad"
   - ~~Si es a un MID, continuar con el paso 3~~
   - ~~Si~~ Es a un CRUD...
- [ ] 2. Hay que interceptar el envío al CRUD de necesidades. Seleccionar un MID adecuado, ojalá de los que ya tenga acceso el cliente de necesidades
    1. Crear el controlador que interceptaría la petición del punto 1
    2. Implementarlo, hacer que reciba tal cual la petición y la reenvíe con el mismo método que se le estaría enviando al CRUD
    3. Consumirlo, que desde el cliente se cambie el endpoint al que le apunta el "Aprobar Necesidad"
- [ ] 3. Hacer el "movimiento presupuestal" que actualice las "cuentas presupuestales"
- [ ] 4. Editar la vista de "Editar la necesidad" para que tenga en cuenta en los límites, los saldos de las "cuentas presupuestales"

**Comment by DanKazuky** [comment]
Se creo el interceptor de la petición de la actualización al CRUD de necesidades para poder seguir con la petición a los movimientos.

[Creación interceptor](https://github.com/udistrital/plan_cuentas_mid/pull/164)

Adicionalmente se cambio en el cliente de necesidades para que la petición sea evaluada por el interceptor.

[Adicion de Interceptor](https://github.com/udistrital/necesidades_cliente/pull/294)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
