### ISSUE TITLE
Vista y funcionalidad Agregar Dependencias a  la Fuente de Financiamiento - David - 10 horas

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#54]
- [x] Crear Vista de Agregar Dependencias al Crud de Fuente de Financiamiento .
- [x] Añadir la funcionalidad y restricción dependiendo del valor de la apropiación del(os) rubro(s) seleccionados   .

**Comment by davidmm07** [comment]
se remueven carpetas no usadas de crud y se genera trigger unico para funciones del componente list, con esto el componente reutilizable se podría personalizar
porcentaje de la tarea 30%

**Comment by davidmm07** [comment]
se crea la vista de dependencias para el listado de fuentes, porcentaje de la tarea 60% , surge la necesidad de crear otro issue en cuanto a la separacion del crud y de opciones personalizadas como por ejemplo (dependencias), #57

**Comment by davidmm07** [comment]
Se agrega vista de dependencias, queda pendiente servicio de las dependencias en ambiente test(pre-producción)

**Comment by davidmm07** [comment]
El servicio de dependencias se modifico en las variables de entorno

**Comment by Soulfilip-UD** [comment]
Así es , se está trabajando ya directamente con el sistema de OIKOS, el código fue revisado y la tarea finalizada, se debe validar respecto a los mockups de fuentes de financiamiento, en caso de que se modifique, se abre de nuevo el Issue 
Proceeding to close Issue 👾
