### ISSUE TITLE
Vista solicitud de la Modificacion Presupuestal , Modulo genralizado para apropiaciones y fuentes - 24 horas - Miguel 

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#56]
Basados en los mockups revisados por la analista , una vez aprovados se empieza el desarrollo de la vista y asimismo de la parte funcional de está.

*** Falta desagregar las funcionalidades en esta vista

**Comment by miguelramirez93** [comment]
Se termina la tarea. Envidencias:
1. Detalle: 
![image](https://user-images.githubusercontent.com/17803254/65392526-81ae3f00-dd3b-11e9-9db6-26ec704121b7.png)
** NOTA ** : Se ajustaron todas las comprobaciones de estado de cada paso para el proceso de registro.

**Comment by miguelramirez93** [comment]
2. Apropiaciones:
![image](https://user-images.githubusercontent.com/17803254/65392552-c4701700-dd3b-11e9-897c-4f261bdc02e4.png)
EN este proceso , según el tipo de movimiento se muestran las cuentas correspondientes. Se hace la sugerencia de determinar dicho comportamiento a nivel de parametros en los tipos y no quemar dicho comportamiento en el código ya que este proceso puede repetirse en el back end

**Comment by miguelramirez93** [comment]
2.1 Tipo de modificación que afecta dos cuentas:
![image](https://user-images.githubusercontent.com/17803254/65392585-01d4a480-dd3c-11e9-88a5-946f3a88c5a3.png)

**Comment by miguelramirez93** [comment]
2.2 Tipo de modificación con una sola cuenta:
![image](https://user-images.githubusercontent.com/17803254/65392591-26c91780-dd3c-11e9-8448-391c6737c4a3.png)

**Comment by miguelramirez93** [comment]
2.3 Seleccion de las cuentas:
![image](https://user-images.githubusercontent.com/17803254/65392607-44967c80-dd3c-11e9-90ed-1b040d68100c.png)
**NOTA** Este componente se muestra cuando se da click al botón "Seleccionar" y se oculta cuando se selecciona una cuenta valida

**Comment by miguelramirez93** [comment]
2.4 Saldos:
![image](https://user-images.githubusercontent.com/17803254/65392636-76a7de80-dd3c-11e9-9f51-74c391994c6a.png)
* Cuando se selecciona una cuenta , se muestra el saldo disponible de la cuenta. Por ahora se esta mostrando la apropiación inicial ya que aun no se cuenta con el servicio de los saldos.

**Comment by miguelramirez93** [comment]
2.5 Resumen de las modificaciones:
![image](https://user-images.githubusercontent.com/17803254/65392665-c25a8800-dd3c-11e9-9e61-64867f2bd312.png)
* Aquí se listan las modificaciones que se desean registrar

**Comment by miguelramirez93** [comment]
3. Guardar
![image](https://user-images.githubusercontent.com/17803254/65392687-00f04280-dd3d-11e9-8e67-2415de92fd66.png)
* Una vez terminado el proceso , se muestra un resumen de los datos ha registrar de la modificación

**Comment by miguelramirez93** [comment]
Para este proceso no se agrego, por ahora, el componente de comprobación de balance del arbol, ya que es recomendable que la lógica que involucra la comprobacion de balance, cuentas que pueden afectarse etc quede en el API y que sea consultada en forma de simulación (no afectando bases de datos y obteniendo un snap-shoot de los datos luego de la modificación) para que en cualquier cambio en la lógica de negocia solo se módifique en un punto y no en ambos frentes (back y front) @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Asociado al Issue [Socialización de modificaciones](https://github.com/udistrital/financiera_documentacion/issues/26)

**Comment by Soulfilip-UD** [comment]
Listo tarea revisada y desplegada.
[Link despliegue](https://pruebaspresupuesto.portaloas.udistrital.edu.co/#/pages/plan-cuentas/modificacion-apropiacion)
Tengo unas dudas:
- [ ] El tipo documento se alimenta de un API ?, del api_core. Por el momento no esta actualizado pero es donde el core ajustara y actualizara el tipo de documentos.

- [ ] En la versión desplegada no se cuenta con una vigencia de apropiaciones aprobada para el 2019 y no se pudo realizar todas las pruebas. No pude tampoco finalizar la aprobación porque aún persiste el error de modificar el valor del rubro apropiación

**Comment by Soulfilip-UD** [comment]
Se estabilizo el desarrollo sobre la rama test, y los cambio están sobre la versión desplegada de test. Los cambios fueron revisados y la tarea está finalizada 

Proceeding to close Issue 👾
