### ISSUE TITLE
Separar Visualización Crud Normal del Crud Personalizado

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#57]
- [x] Crear proceso para separar visualización crud normal del crud personalizado

**Comment by davidmm07** [comment]
Tarea a revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
como dice la documentación de la [generalización del CRUD](https://github.com/udistrital/presupuesto_cliente/issues/53) se separan pero se trabajan en conjuntos las respectivas propiedades del modulo con las del crud generalizado.
Tarea finalizada, revisada, aprobada y desplegada

Proceeding to close Issue 👾
