### ISSUE TITLE
Ajustes cliente presupuesto

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#59]
Tomando en cuenta las sugerencias de la ultima socializacion se plantearon los siguientes ajustes:

- [x] Revisar Ortografía

- [x]  Highlight rubro seleccionado en el arbol de rubros al darle click y ver sus detalles

- [x]  API:plan_cuentas_mongo_crud -> Corregir mensaje, se duplico el rubro, pero devuelve un estado de creado nuevamente

- [x]  Mover boton 'Apropiación Inicial'

- [x]  Cambiar título 'Preasignación Apropiaciones iniciales' -> 'Preasignar Apropiaciones vigencia '''2020'''

- [x] No se está permitiendo hacer modificaciones en los rubros

**Comment by Soulfilip-UD** [comment]
Se ajusta el cliente para la presentación con el vice, queda por ajustar los 3 primeros items.

**Comment by Soulfilip-UD** [comment]
Hay una nueva revisión del sistema por parte del analista , se revisara  lo requerido y en caso de que sea posible realizar los cambios rapidamente se avanzara

**Comment by Soulfilip-UD** [comment]
Porcentaje de la tarea 50%

**Comment by Soulfilip-UD** [comment]
- [ ] Se avanzo con la tarea y resaltar el rubro seleccionado ya funciona, tiene unos ajustes por realizarse a nivel de rubros hijos, 

- [ ] la ortografía y redacción la esta revisando Viviana y nos estregara un compilado

- [ ] Titulo ajustado 'Preasignar Apropiaciones vigencia '''2020'''

- [ ] Asimismo Mover boton 'Apropiación Inicial' quedo lista

- [ ] Y la tarea API:plan_cuentas_mongo_crud -> Corregir mensaje, se duplico el rubro, pero devuelve un estado de creado nuevamente, ya quedo corregida está semana (ya desplegada)

**Comment by Soulfilip-UD** [comment]
Tarea en un 85%

**Comment by davidmm07** [comment]
Al ingresar el valor de la apropiación y preasignarlo, se genera el siguiente error 
`invalid memory address or nil pointer dereference`
 Codigo del Status: 500 Internal Server Error.
Se prueba en local y también se evidencia el error desde el api plan_cuentas_mongo_crud.

**Comment by davidmm07** [comment]
Tarea  a revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
- [ ] La edición del rubro apropiación principalmente falla por la construcción del objeto que se está enviando, corregirla. Y volver a desplegar en test  para revisión.

Estado de la tarea 83%

**Comment by Soulfilip-UD** [comment]
Cambios realizados y revisados en la versión de test
Tarea Finalizada 
Proceeding to close Issue 👾
