### ISSUE TITLE
Generar vista de árbol de rubros

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#6]
Realizar la vista del árbol de rubros en el cliente del susbsistema de presupuesto

- [x] Añadir sección de Rubros al menú principal

- [x] Visualización del árbol de rubros

- [x] Detalle del rubro seleccionado

**Comment by macaguegi** [comment]
Se añade el árbol de rubros en una card y en otra card se despliega detalle de información en caso de seleccionar un rubro en el árbol.

**Comment by davidmm07** [comment]
Faltaria integrar el cliente con el middleware (mid) del plan de cuentas , se sugirere tomar el endpoint:
1. si no hay rama:
```
 v1/rubro/ArbolRubros/:unidadejecutora/?rama=
```
2. si hay rama: 
```
v1/rubro/ArbolRubros/:unidadejecutora/?rama=ramaaconsultar
```

**Comment by miguelramirez93** [comment]
Se realiza la revisión de la tarea . No se tienen observaciones
