### ISSUE TITLE
Vista listado y boton de solicitud para CRP

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#63]
- [x]  Implementar Smart Table , cargar datos de Solicitud CRP 

- [x] Crear botón que lleve al usuario al formulario de Registro de Solicitud CRP

**Comment by macaguegi** [comment]
Se completa esta tarea :stars:  . Se solicita revisión de líder técnico @Soulfilip-UD .

**Comment by Soulfilip-UD** [comment]
Confirmar si se deben ver las vistas de la siguiente manera :
<img width="963" alt="Screen Shot 2019-09-30 at 3 12 06 PM" src="https://user-images.githubusercontent.com/50924615/65913002-c4ec5b80-e394-11e9-9d2f-6686e21b806c.png">
<img width="702" alt="Screen Shot 2019-09-30 at 3 11 50 PM" src="https://user-images.githubusercontent.com/50924615/65913003-c4ec5b80-e394-11e9-8567-3a2c909acf92.png">

**Comment by Soulfilip-UD** [comment]
Código revisado y funcionalidad revisada
Deja está opción como un radio button, ya que no pueden ser los 2 estados a la vez:
<img width="574" alt="Screen Shot 2019-09-30 at 3 14 32 PM" src="https://user-images.githubusercontent.com/50924615/65913297-3b895900-e395-11e9-8857-549aec9744a5.png">

**Comment by macaguegi** [comment]
Se tienen en cuenta los ajustes solicitados por el líder técnico. Estado de la tarea : 90%.

**Comment by Soulfilip-UD** [comment]
porfa revisa que los cambios se están desplegando satisfactoriamente en test: https://pruebaspresupuesto.portaloas.udistrital.edu.co/#/pages/plan-cuentas/crp

**Comment by Soulfilip-UD** [comment]
son dos cosas puntuales : 

- [x]  el texto de Área Funcional en la tabla de solicitudes

- [ ]  la fecha en el detalle que tenga formato DD/MM/YYYY

**Comment by Soulfilip-UD** [comment]
Proceeding to close Issue 👾 
continua Issue #161
