### ISSUE TITLE
Implementar la paleta de colores , tipografía y el logo

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#64]
Ajustar los estilos del cliente de Presupuesto para que se adapten a la plantilla proporcionada.

**Comment by macaguegi** [comment]
Se solicita a líder técnico @Soulfilip-UD todo el material relacionado con la plantilla. Estado de la tarea : 5%.

**Comment by Soulfilip-UD** [comment]
[Logo_e_iconos.zip](https://github.com/udistrital/presupuesto_cliente/files/3673455/Logo_e_iconos.zip)
[Lineamientos Kronos.docx](https://github.com/udistrital/presupuesto_cliente/files/3673456/Lineamientos.Kronos.docx)

Adjunto paleta de colores y logo

**Comment by Soulfilip-UD** [comment]
Debido al contratiempo por las protestas y el robo del computador, está tarea se finaliza en el sprint del 30 de Septiembre al 7 Octubre

**Comment by macaguegi** [comment]
Se crea el theme KRONOS_THEME con los colores de la paleta proporcionados por Viviana . Tambien se ajustó el header y el footer de acuerdo a la imagen disponible en el documento. 

**Imagen Viviana**
![image](https://user-images.githubusercontent.com/12780939/65995016-3e01b680-e45a-11e9-855c-c92d8526d205.png)


**Presupuesto Cliente**
![image](https://user-images.githubusercontent.com/12780939/65995033-46f28800-e45a-11e9-8eda-ff083b24eecd.png)


Nota : Aún quedan ajustes en los estilos (CSS) del footer, por lo cual se solicita ayuda de líder técnico @Soulfilip-UD . Estado de la tarea : 90%

**Comment by macaguegi** [comment]
Respecto al footer , el equipo de Interfaz Unica (Core) comenta que ya existe el componente listo y están en el proceso de distribuirlo para todos los clientes de la Oficina. Se termina con esta tarea. Estado 100%,

**Comment by Soulfilip-UD** [comment]
Ya que el equipo de core ya posee el componente para ajustar los elementos del footer se da por finalizada la tarea.

Cambios desplegados en test
Proceeding to close Issue 👾
