### ISSUE TITLE
Creación Mockup's Apropiaciones Iniciales ( con precargue de apropiación siguiente Vigencia)

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_cliente#7]
Se generara el documento y el proyecto editable en herramienta de diseño para los componentes visuales de apropiación inicial.

- [x]  Generar vistas de apropiación inicial previstas para Kronos
- [x]  tomar en cuenta los ajustes y sugerencias hechas para el modulo por el arquitecto en el [documento de revision](https://docs.google.com/document/d/1Ej_D4Xrx1XQWa1C8aXVqaJq6btC0qCsriHSkXWaG4Q4/edit)
- [x]  Subir las imágenes, el documento y el proyecto en caso de que se requieran ediciones

**Comment by CarlosGutierrezArdila** [comment]
se adjunta [documento](https://docs.google.com/document/d/1Me729vCE7k1MOl-K4O_JKu33Ed05RlmpRqvwYb9MOEY/edit#) con las imágenes y los respectivos comentarios atendiendo a las sugerencias del arquitecto

**Comment by CarlosGutierrezArdila** [comment]
se adjunta [archivo](https://drive.google.com/open?id=1F51xVUSqYCYsv8JqrmE9Dv6zerVjmx2y) del proyecto trabajado en la herramienta GIMP2.10 para futuras modificaciones

**Comment by miguelramirez93** [comment]
Revisado. No se tienen observaciones.
