### ISSUE TITLE
 Vista detalle de la solicitud de CDP 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_cliente#70]
- [x] implementar la vista de consultar detalle de solicitud CDP
- 5 horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
Estado tarea 90% a falta de ajustes menores

**Comment by CarlosGutierrezArdila** [comment]
Se finaliza la tarea y se deja para revision de LT @Soulfilip-UD  no se hace PR pues se continua el trabajo en la rama para tareas de la siguiente semana

**Comment by CarlosGutierrezArdila** [comment]
![image](https://user-images.githubusercontent.com/32855979/65915000-18ac7400-e398-11e9-909b-5f33480d289a.png)
vista listado
![image](https://user-images.githubusercontent.com/32855979/65915083-41cd0480-e398-11e9-89ea-a3cfbafc4011.png)
![image](https://user-images.githubusercontent.com/32855979/65915127-5dd0a600-e398-11e9-99cd-8cf456f0fcad.png)
Vista detalle

**Comment by Soulfilip-UD** [comment]
:Perfect:
tarea revisada desde hace una semana , hacia falta el despliegue en test
tarea Finalizada
Proceeding to close Issue 👾
