### ISSUE TITLE
Alerta de CDP expedido y boton intención de descarga de pdf 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_cliente#71]
- [x] implementar alerta de CDP expedido
- [x] mostrar botones para visualizar pdf
- 4 horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
Se finaliza la tarea y se deja para revision de LT @Soulfilip-UD  no se hace PR pues se continua el trabajo en la rama para tareas de la siguiente semana

**Comment by Soulfilip-UD** [comment]
![alertaCDP](https://user-images.githubusercontent.com/50924615/65983483-308d0200-e443-11e9-94c3-048170995d60.png)

Tarea revisada y finalizada

Proceeding to close Issue 👾
