### ISSUE TITLE
Crear Interfaz para listar las modificaciones presupuestales

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#72]
- [ ] Crear Interfaz para listar las modificaciones presupuestales

**Comment by Soulfilip-UD** [comment]
Estado de la tarea en el momento 0%

**Comment by davidmm07** [comment]
Aun no se ha trabajando en esta tarea, debido a qué se ha dado prioridad a Los ajustes del hito 1

**Comment by Soulfilip-UD** [comment]
La tarea se realizo en otro Issue

Proceeding to close Issue 👾
