### ISSUE TITLE
Resaltar el rubro seleccionado

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#73]
- [x] Resaltar el rubro seleccionado al componente generico de arbol

**Comment by davidmm07** [comment]
Tarea a revision @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
PR revisado y aprobado para mezclarse, no borre la rama debido al bug que comentaba en el daily, tarea en un 95%

**Comment by davidmm07** [comment]
bug solucionado , tarea  a revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Tarea satisfactoria, bug eliminado 
Buen trabajo

Proceeding to close Issue 👾
