### ISSUE TITLE
Crear opción para guardar dependencias creadas o editadas en la fuente de financiamiento

### ISSUE THREAD

**Issue by davidmm07** [udistrital/presupuesto_cliente#74]
- [x] Crear vista y funcionalidad para agregar el valor definido por hacienda a la fuente de financiamiento.
- [x] Crear opción para agregar el valor del rubro y descontarlo al valor definido por hacienda.
- [ ] Crear servicios del cliente que conecten al api para editar,consultar y guardar las dependencias.
- [ ] Generar botón de guardar cambios.

**Comment by davidmm07** [comment]
Porcentaje de tarea 30%

**Comment by Soulfilip-UD** [comment]
tentativamente 15 horas

**Comment by Soulfilip-UD** [comment]
Porcentaje de la tarea a la fecha 30%

**Comment by davidmm07** [comment]
Porcentaje de la tarea 50%

**Comment by davidmm07** [comment]
Se extiende esta tarea ya qué a nivel de API se requiere actualizar la estructura y adaptarla para qué funcione Los procesos de modificacion presupuestal vistos en la reunión del martes 8 de octubre

**Comment by Soulfilip-UD** [comment]
La HU se modifico y el flujo también no se están asignando valores a la dependencia


Proceeding to close Issue 👾
