### ISSUE TITLE
Generar vista de Procesos de Apropiaciones.

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#8]
Realizar la vista de los procesos de apropiaciones en el cliente del subsistema de presupuesto

- [x] Añadir sección de Apropiaciones al menú principal

- [x] Insertar componente de árbol de rubros

- [x] Crear tarjeta para consultar apropiaciones asociadas a un rubro

- [x] Crear ventana modal para registrar una apropiación a un rubro

**Comment by macaguegi** [comment]
Se culmina tarea de vista de apropiaciones iniciales. Sin embargo , se hablo con el líder técnico Felipe @Soulfilip-UD y con el arquitecto John @corio27 y se acordó que se deben modificar los modulos para que todo el plan de cuentas se maneje sobre una misma vista.

**Comment by Soulfilip-UD** [comment]
El Issue continua en el Issue #17 , se finaliza este.
