### ISSUE TITLE
Al seleccionar una apropiación y querer editar su valor, este no se actualiza - 3 horas - MIguel

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/presupuesto_cliente#83]
- [x] corregir seleccion y actualización de apropiaciones

**Comment by miguelramirez93** [comment]
se realizó por error commit directo a dev https://github.com/udistrital/presupuesto_cliente/commit/9e9419274b3cc754ce02b01d90aa67069595f465

**Comment by miguelramirez93** [comment]
@Soulfilip-UD  la tarea se ha finalizado, perodón por el commit directo a dev :(

**Comment by Soulfilip-UD** [comment]
Desarrollo revisado sobre el commit asociado y 'aprobado', 

Tarea finalizada
Proceeding to close Issue 👾
