### ISSUE TITLE
Visualizar documento de CDP expedido estatico 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_cliente#84]
- [x] mostrar por medio del navegador un PDF de CDP expedido estatico que se alojara en el proyecto
- 5 horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
Se crea un componente reutilizable para mostrar documentos en PDF a partir de un titulo y un enlace de documento:
![image](https://user-images.githubusercontent.com/32855979/65993997-fc700c00-e457-11e9-9913-e67e33b60afb.png)
se puede usar en los componentes de angular en su plantilla de la siguiente forma: 
```html
<ngx-pdfviewer  [tituloPDF]="tituloPDF" [enlacePDF]="enlacePDF" (goBack)="mostrandoPDF=$event"></ngx-pdfviewer>
```

**Comment by CarlosGutierrezArdila** [comment]
Tarea finalizada 100% para revision de LT @Soulfilip-UD 4H

**Comment by Soulfilip-UD** [comment]
Desarrollo revisado y aprobado, asimismo se revisa la tarea desde el cliente y aprobado.
Muy buen apunte tener el componente reusable para con documentos pdf!! 👍 

Tarea Finalizada
Proceeding to close Issue 👾
