### ISSUE TITLE
Crear componente con solicitud  de CDP 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/presupuesto_cliente#85]
- [x] crear componente acorde a los mockups que permita ver detalle de solicitud de CDP

**Comment by CarlosGutierrezArdila** [comment]
Se generaliza el componente de vista para que permita ver el detalle de la solicitud y del CDP expedido según sea el caso, para una solicitud: 
![image](https://user-images.githubusercontent.com/32855979/65993729-6a680380-e457-11e9-8b28-a633e26a44ae.png)
![image](https://user-images.githubusercontent.com/32855979/65993790-84094b00-e457-11e9-99db-5dd3d112210c.png)
![image](https://user-images.githubusercontent.com/32855979/65993845-9e432900-e457-11e9-8d10-cf81ce46ddc7.png)

Para el caso de documento expedido: 
![image](https://user-images.githubusercontent.com/32855979/65993569-1fe68700-e457-11e9-9bee-11e22d4c0b8b.png)
![image](https://user-images.githubusercontent.com/32855979/65993609-2e34a300-e457-11e9-9e7c-3d3ae62a3e10.png)
![image](https://user-images.githubusercontent.com/32855979/65993634-3d1b5580-e457-11e9-86f4-c1d954f310e3.png)

**Comment by CarlosGutierrezArdila** [comment]
Tarea finalizada 100% para revision de LT @Soulfilip-UD 10H

**Comment by Soulfilip-UD** [comment]
Desarrollo revisado y aprobado, asimismo se revisa la tarea desde el cliente y aprobado.

Tarea Finalizada
Proceeding to close Issue 👾
