### ISSUE TITLE
Justificar los valores a la derecha y agregar el $ 

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#87]
Se solicita : 

- [x] Crear un estilo para que todos los valores de moneda salgan alineados a la derecha y con las cifras decimales correctamente agregando tambien el signo pesos.

- [x] Añadir esta clase a todos los campos de moneda que hayan en el cliente  :octopus:

**Comment by macaguegi** [comment]
Se crea el estilo *moneyField* que alinea el valor a la derecha y antepone un signo $ al numero. Se aplica este estilo en Apropiaciones y se visualiza de la siguiente manera 

![image](https://user-images.githubusercontent.com/12780939/66000591-5fb46b00-e465-11e9-9554-548a9388576d.png)


Estado de la tarea : 70% . Queda pendiente aplicar estilos a Fuentes de Financiamiento, Solicitud CDP y Solicitud CRP

**Comment by macaguegi** [comment]
Se aplica estilo de moneda a Gestión de CRPs y CDPs . Queda pendiente todo el submódulo de Fuentes de Financiamiento y Modificaciones Presupuestales . Estado de la tarea : 90%

**Comment by Soulfilip-UD** [comment]
@davidmm07 debió realizar el ajuste sobre Fuentes de financiamientos, rubros y apropiaciones. Queda solamente aplicarlo sobre modificaciones

Estado de la tarea :95%

**Comment by macaguegi** [comment]
Se instala paquete para agregar una máscara de moneda a los campos input y se aplica la misma **currencyMask** en todos los formularios y campos de moneda. Estado de la tarea : 100% . Se solicita revisión de líder técnico @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
se aplica sobre modificaciones presupuestales con el paquete que instalo Maria Camila y se hace merge a la ram dev, en local todo OK

Tarea finalizada
Proceeding to close Issue 👾
