### ISSUE TITLE
Registrar una solicitud de CRP

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#88]
Se requiere

- [x] Realizar el POST para el registro de una Solicitud de CRP que se diligencia en el formulario de Solicitar CRP :leopard:

**Comment by macaguegi** [comment]
Se revisa la estructura y se crea el modelo de Solicitud CRP en el cliente para poder enviar un objeto a través del Request Manager. Estado de la tarea 5% .

**Comment by Soulfilip-UD** [comment]
Listo @macaguegi , desconozco en el momento el endpoint o cliente desde el que se actualizan los documentos, ya te estaré informando. Porfa explicame en detalle la información que hace falta del contratista, es asociar el API de personas a kronos en wso2?
