### ISSUE TITLE
Crear componente con solicitud del CRP

### ISSUE THREAD

**Issue by macaguegi** [udistrital/presupuesto_cliente#89]
Se solicita 

- [x] Creación de un componente en forma de tabla en el cual se pueda visualizar toda la información correspondiente a la Solicitud de un Certificado de Registro Presupuestal :panda_face:

**Comment by macaguegi** [comment]
Se muestra a modo de tabla la información de una solicitud de Certificado de Registro Presupuestal . 
Pendientes próximo sprint : 

- Mostrar el nombre del compromiso (Por definir modelo de Compromisos Mongo) 

- Cargar el nombre del contratista (Por definir si se consume servicio del CORE o AGORA) .


 El desarrollo se puede visualizar a través de la ruta **plan-cuentas/solicitudescrp** , se selecciona la solicitud a visualizar y se muestra la siguiente ventana : 

![image](https://user-images.githubusercontent.com/12780939/66095280-9faa4980-e55c-11e9-9e67-05ea940b8969.png)

Estado de la tarea : 100% . Se procede a hacer el merge a la rama DEV y se solicita revisión de líder técnico @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Desarrolllo revisado y asociado a la rama dev satisfactoriamente. 
El nombre de compromiso lo definimos desde el mismo servicio de tipo _documento, ya te informare del cliente designado para la administración, y debo consultar la duda si usar el API de persona de CORE o AGORA.

Doy la tarea por terminada ya que el desarrollo asociado al issue está finalizado, y los ajustes que quedan se realizan desde wso2 y desde el cliente para la administración de tipo_documento

Tarea Finalizada
Proceeding to close Issue 👾
