### ISSUE TITLE
Integración cliente con Mid API de Rubros con WSO2

### ISSUE THREAD

**Issue by miguelramirez93** [udistrital/presupuesto_cliente#9]
Se requiere integrar los desarrollos a nivel de servicios con el cliente , tomando en cuenta la integración del API Manager (WSO2)

- [x] Creación de unico punto de consulta http .
- [x] implementación de consultas http a mid api para el proceso de rubros.

**Comment by Soulfilip-UD** [comment]
Agregar cambios a la rama dev como PR para finalización de la tarea.

**Comment by Soulfilip-UD** [comment]
Tarea finalizda se procede a cerrar el Issue
