### ISSUE TITLE
Ajuste Rubros Presupuestales- 5 horas - David

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#95]
Basados en el Issue (591)[https://github.com/udistrital/financiera_cliente/issues/591] se tienen los siguientes ajustes: 

- [x] Cuando se selecciona un rubro para crear un hijo, colocar algo que resalte.**realizado**

- [x] Entiendo que si quiero editar el rubro ya creado, siempre y cuando no tenga movimientos, debe permitirme cambiar hasta el código y no lo está permitiendo, no habilita el recuadro del código.**Dentro del manual habria que aclarar que para el corregir el codigo es mejor eliminar el rubro incorrecto y volver a crearlo**
- [x] Al continuar en la creación de un rubro hijo hasta un siguiente nivel, aparentemente lo crea por que se genera la alerta, pero cuando se va a consultar no aparece. **Se encuentra el escenario mencionado y se corrige**
- [x] Una vez se creen todos los hijos de un rubro hasta último nivel y me ubico en él, debe dejarme ver el rubro completo. **El escenario no se evidencia que este fallando**
- [x] Recuerden que el recuadro Entidad debe decir Centro Gestor y en el recuadro de Unidad ejecutora debe decir Área Funcional (esto se lo aclaré al ing. Felipe para socialización con los desarrolladores) **Ya esta definido, sin embargo se sugiere definir cuales pueden ser los posibles Centros Gestores y Areas Funcionales para tenerlos en cuenta en los diferentes servicios**
- [x] Valores a la derecha y por favor colocar el punto de miles de pesos. **Falta subir algunos cambios a preprod**
- [x] No se observa para que vigencia se está creando el rubro. **Es transparente para cualquier vigencia, lo que importa es cuando se construyen los valores de apropiación(preasignación)** 
- [x] Por favor tener en cuenta la longitud de caracteres para cada nivel del rubro **En revisión** 
- [x] No se observa en ninguna parte que nivel del rubro estoy creando **En revisión**

**Comment by Soulfilip-UD** [comment]
En el momento quedan 3 de 9 ajustes:
- [ ] Valores a la derecha y por favor colocar el punto de miles de pesos. **Falta subir algunos cambios a preprod**
- [ ] Por favor tener en cuenta la longitud de caracteres para cada nivel del rubro **En revisión** 
- [ ] No se observa en ninguna parte que nivel del rubro estoy creando **En revisión** 

Tarea en un 66%

**Comment by davidmm07** [comment]
Se resuelve ajuste (Por favor tener en cuenta la longitud de caracteres para cada nivel del rubro) a partir de este issue https://github.com/udistrital/plan_cuentas_mongo_crud/issues/111

**Comment by davidmm07** [comment]
Tarea a revisión @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Se tiene en cuenta las observaciones del analista y efectivamente se aplican los ajustes, resaltamos el hecho de usar el ceros a la izquierda para cumplir con el número de dígitos por nivel, y todos los errores de ortografía se corregirán basados en el informe realizado por Viviana.

Tarea finalizada
Proceeding to close Issue 👾
