### ISSUE TITLE
Ajustes Apropiaciones - 5 horas  - David

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/presupuesto_cliente#96]
Basados en el Issue (591)[https://github.com/udistrital/financiera_cliente/issues/591] se tienen los siguientes ajustes: 

- [x] Al desplegar el árbol en la preasignación, se ve partido el rubro, es decir no es clara la visualización para que el rubro se vea completo 
- [x] Acá si me aparecen los rubros que cree en Rubros Presupuestales hasta el cuarto nivel
En la comprobación por favor cambiar EGRESOS por GASTOS
- [x] Por favor tener en cuenta las tildes
- [x] El titulo de comprobación, ingresos y egresos por favor disminuir la fuente por que está muy grande 
- [x] En la comprobación por favor colocar miles de pesos
- [x] Al realizar la aprobación de la apropiación inicial esta generando un error
- [x] Se sugiere resaltar el rubro

**Comment by Soulfilip-UD** [comment]
Al momento quedan 5 de 7 ajustes:
- [ ] Al desplegar el árbol en la preasignación, se ve partido el rubro, es decir no es clara la visualización para que el rubro se vea completo  **definir mejor esta observación, la información se ve clara** 
- [ ] Por favor tener en cuenta las tildes **se esta revisando con Viviana** 
- [ ] El titulo de comprobación, ingresos y egresos por favor disminuir la fuente por que está muy grande  **pendiente** 
- [ ] En la comprobación por favor colocar miles de pesos **pendiente** 
- [ ] Al realizar la aprobación de la apropiación inicial esta generando un error **pendiente** 

Tarea en un 29%

**Comment by davidmm07** [comment]
Porcentaje de la tarea 95%

**Comment by Soulfilip-UD** [comment]
Se limpia la colección de apropiaciones, se aprueba una apropiación para el 2019, asimismo se agrega al rubro 3-03-1-15 la fuente y productos de prueba para realizar efectivamente las pruebas con el sistema de necesidades. La rama de test se actualiza con todos los cambios.

Se corrige asimismo el endpoint de aprobacion_masiva que quedo mal registrado en wso2, los errores de ortografía se corregiran con el informe detallado de Viviana.

Al momento de cerrar la tarea surge un bug no asociado a este Issue que se resolvera en un nuevo Issue: "Si todos los rubros no tienen todos los mismos subniveles de rubros hijos, no se pueden visualizar los que tengan más"

Tarea Finalizada y desplegada en test
Proceeding to close Issue 👾
